### ISSUE TITLE
Ps3 games unrecognised system error

### ISSUE THREAD

**Issue by faintuk** [avjui/Gamez#10]
I have added a few ps3 and when gamez goes off to search for these the logs appears to come up with an unrecognised system and so no games are snatched

**Comment by avjui** [comment]
Here PS3 games have no problem .
In settings there is a checkbox for debug please enable this and post the log.

Thanks

**Comment by faintuk** [comment]
Ive enabled debug an here is the error i get for a ps3 game

DEBUG : Debug: None 2012-04-24 17:27:29
DEBUG : Debug: None 2012-04-24 17:27:29
DEBUG : Debug: 319  2012-04-24 17:27:29
Retrieving the latest version   2012-04-24 17:27:28
Checking to see if a new version is available   2012-04-24 17:27:28
Unrecognized System 2012-04-24 17:27:28
Checking for game [Heavy Rain] on NZB Matrix    2012-04-24 17:27:28
Searching for game: Heavy Rain  2012-04-24 17:27:28
Searching for games 2012-04-24 17:27:28
DEBUG : Debug: None 2012-04-24 17:27:25
DEBUG : Debug: None 2012-04-24 17:27:25
DEBUG : Debug: None

**Comment by avjui** [comment]
I have updatet NZBMatrix for PS3 and PC please can you test it. If there more bugs please post one more the DebugLog.

**Comment by faintuk** [comment]
just tested the newest version and its working fine now
