### ISSUE TITLE
Please add the ability to set console region.

### ISSUE THREAD

**Issue by KruyKaze** [avjui/Gamez#11]
Like USA/NTSC as releases are not compatible with all consoles.
Thanks.

**Comment by avjui** [comment]
What do you think how could i implement this feature? I don´t know how good the nzb names are. The only thing i can implement is to look on the filename and search for "USA" EUR" JPN" perhaps also can look " PAL" NTSC". What do you think?

**Comment by KruyKaze** [comment]
That could be a solution , mine is a US console so search should eliminate PAL/JPN/FRENCH/ITA/ASIA/SPANISH/ but accept RF if it doesn't contain those words.
Except some releases do not say what region they are. The most accurate way is to use http://www.abgx.net/filename/?ch=6
So which ever is easier I guess.
Thanks.

**Comment by avjui** [comment]
Ok I will have a look at that. Can anybody say for with console this is relevant. Only XBOX or also WII and PS3

**Comment by KruyKaze** [comment]
The PS3 releases are region FREE (but you probably don't want releases for other languages)
The Xbox and Wii are region locked.
Thanks.

**Comment by KruyKaze** [comment]
I saw you started implementing "required words" to search.
I think it works best to use "avoided words" because if we used required words like RF or USA or NTSC

Prototype.2.RF.SPANiSH.XBOX360-iND   <--- will be downloaded (we don't want it)

Prototype.2.XBOX360-COMPLEX            <--- will NOT be downloaded  (we want this release)

So just add a blacklist where we can add (Pal,Spanish,french etc.....) That is guaranteed to work.
Thanks.

**Comment by avjui** [comment]
Yesterday i also come to this opinien. I will implement this feature in the next week

**Comment by KruyKaze** [comment]
Nice thanks
On Apr 29, 2012 11:49 PM, "avjui" <
reply@reply.github.com>
wrote:

**Comment by avjui** [comment]
I have added it for newznab and for nzb.su please can you test it. For NZB Matrix I need a output of a api call to implement This feature.

**Comment by KruyKaze** [comment]
Alright Success!
Searched for a game, found it sent it to sabnzbd , set the category
correctly and post processing script(not sure what it does)
It was the wrong language but that will be fixed with a black list as you said.
Thanks very much.
P.S: What does the processing script do?

On Mon, Apr 30, 2012 at 1:33 PM, avjui
reply@reply.github.com
wrote:

**Comment by avjui** [comment]
When download is succes it change the status  of the game in gamez to downloaded.
I close the ticket

**Comment by KruyKaze** [comment]
Thanks
On May 1, 2012 1:41 AM, "avjui" <
reply@reply.github.com>
wrote:
