### ISSUE TITLE
Won't load on Win 7 64bit

### ISSUE THREAD

**Issue by simonk83** [avjui/Gamez#12]
I had the previous version working just fine, but after updating to the GameDB branch I can't load Gamez at all.  I just get a black console window.

Let me know what other info you need :)

**Comment by avjui** [comment]
Hi

Please can you check what error the console give. To run python programs easy from cmd add following.
Assuming you have Python2.7 installed 

Goto the Start Menu

Right Click "Computer"

Select "Properties"

A dialog should pop up with a link on the left called "Advanced system settings". Click it.

In the System Properties dialog, click the button called "Environment Variables".

In the Environment Variables dialog look for "Path" under the System Variables window.

Add ";C:\Python27" to the end of it. The semicolon is the path separator on windows.

Click Ok and close the dialogs. 

Now open up a new command prompt and type "python" $THEPATHTOGAMEZ\Gamez.py and see what he say. please post the error

**Comment by simonk83** [comment]
Aaaaahh, I see.  It's because gamez.ini is missing from my User directory apparently :)

**Comment by simonk83** [comment]
Which ini does it use?  The one in the Users directory, or the one in the Gamez folder with everything else?

**Comment by avjui** [comment]
The configfile in the Gamez folder. When you have problem please post the console log

**Comment by simonk83** [comment]
Ok, I was still having some issues, so I completely removed all the Gamez files, and repulled.   After running again fresh, I get the following in the console:

C:\Users\Simon>python G:\Handies\Gamez\gamez.py
------------------- launch Browser ( 127.0.0.1:8085) -------------------

It's been sat there for about 20 mins now, and there's no access to the Gamez page via the browser unfortunately.   

Not too sure what I'm missing (for reference, I have SAB, Couchpotato v1 and v2, Sickbeard, Headphones and LazyLibrarian running with no issues, so I assume it's not an issue with my machine)....

Let me know if there's anything you need me to try,

**Comment by avjui** [comment]
The problem is i have no win7 64bit. Please can you checkout the different commits. Perhaps we find the commit that brings the problem.

**Comment by simonk83** [comment]
Sure, I'll try and do that today for you

**Comment by simonk83** [comment]
Phew.   Well I got it to run but it was a bit of a mission.   Essentially, as far as I can gather, these are the issues:

After a completely fresh pull (all files deleted from the Gamez directory, and the Gamez.db deleted from C:\Users\Username), Gamez fails to create the new Gamez.db and Gamez.ini in the User directory

After first run, the Gamez.db is created, but it's totally empty (0 bytes) and not a valid sqlite DB

After copying the Gamez.db from the Gamez directory into the Users directory, it'll sit on a blank screen in the console

After querying the gamez_log table in a SQLite browser, it seems Gamez was trying to find the download directory from SAB.  This of course will always fail as it hasn't been set up yet.  So I manually entered the path in the Gamez.ini

Then after running Gamez.py, you get a message about Gamez.ini missing from the User directory, so I manually copied the version from the Gamez directory across.

This time, running Gamez.py works as expected.

So yeah, there are some issues with regards to paths in Windows, and also with regards to the SAB download directory being searched for before having a chance to set it in the web page.

Hope that helps :)

**Comment by simonk83** [comment]
Also, in the Gamez.ini, the default port for Sab is set to 8081.  That's actually Sickbeard, it should be 8080.

**Comment by simonk83** [comment]
Now I just switched to TheGameDB branch and I'm having similar issues.  After setting the SAB config stuff in the Gamez.ini (this time in the Gamez directory), I'm getting the following:

Traceback (most recent call last):
  File "G:\handies\gamez1\gamez.py", line 285, in <module>
    RunApp().RunWebServer()
  File "G:\handies\gamez1\gamez.py", line 37, in RunWebServer
    css_webinterface = "css/" + config.get('SystemGenerated','webinterface').rep
lace('"','')
  File "C:\Python27\lib\ConfigParser.py", line 332, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'webinterface' in section: 'SystemGenerate
d'

EDIT:  Ah, I see, interesting.  Seems it's jumping back and forth between the Gamez.ini in the Gamez directory, and the Gamez.ini in the Users directory...  the Webinterface option was missing from the ini in the users directory.

Copying the ini from the Gamez directory to the Users directory sorted it out.

So essentially, Gamez just isn't creating these files in the Users directory properly, or at all.

**Comment by avjui** [comment]
Hi

Here i have a win 7 32bit and I can not see anything like you. Wy do you have a User Directory for this? I have the Gamez.ini in the Gamez directory and there are no problems. The issue with non exist DB i have fix a time ago.  They only thing is when i delete Gamez.db and Gamez.ini first start fails because Gamez.ini will be created later. But when i start it a second one all is right.

**Comment by simonk83** [comment]
No idea why it wants to use the user directory (c:/users/simon) but it's something in the code as I get an error message in the console that gamez.ini is missing from c:/users/simon.

It's nothing I've done as this is a fresh clone of the repo :)

**Comment by avjui** [comment]
I have tested on win 7 64bit and here is alright. Please get lastet version and start the aplication from the folder directly.
