### ISSUE TITLE
Can't connect to sab

### ISSUE THREAD

**Issue by KruyKaze** [avjui/Gamez#13]
I keep getting this error:
Unable to connect to Sanzbd: http%3A//localhost%3A8092/sabnzbd/api%3Fmode%3Dget_config%26apikey*****************************************section%3Dmisc%26keyword%3Dscript_dir

**Comment by avjui** [comment]
Here i don´t can see any bug. Please can you check in sabnzbd if there is define a script dir. 
Have a look in Settings -> Folders -> Post-Processing Scripts Folder.

**Comment by KruyKaze** [comment]
Yes the script folder is set.

**Comment by avjui** [comment]
Is this new or exist this with original Gamez also!

**Comment by KruyKaze** [comment]
I never tried the old one
On Apr 26, 2012 11:21 PM, "avjui" <
reply@reply.github.com>
wrote:

**Comment by avjui** [comment]
Please can you check the old one. Thanks

**Comment by KruyKaze** [comment]
I'll try it.
Thanks

On Fri, Apr 27, 2012 at 4:51 AM, avjui
reply@reply.github.com
wrote:

**Comment by KruyKaze** [comment]
Old one gives the same error.
By the way I am using Ubuntu 11.10 64bit.

**Comment by avjui** [comment]
Here all is right, I don´t find anything. 

Please can you change for testing  in lib/GameTasks.py at Line 64

from  
          responseObject = opener.open(url)
in
          responseObject = opener.open(urllib.unquote(url))

Thanks

**Comment by KruyKaze** [comment]
I get this error when i do that:
Traceback (most recent call last):
  File "Gamez.py", line 5, in <module>
    from lib.WebRoot import WebRoot
  File "/home/k/Gamez/lib/WebRoot.py", line 15, in <module>
    from GameTasks import *
  File "/home/k/Gamez/lib/GameTasks.py", line 102
    responseObject = opener.open(urllib.unquote(url))
                                                    ^
IndentationError: unindent does not match any outer indentation level

Thanks

On Sat, Apr 28, 2012 at 12:14 PM, avjui
reply@reply.github.com
wrote:

**Comment by avjui** [comment]
Please checkout the Gametasks branch and post the consolelog and the debug log. I hope we find the bug.

**Comment by KruyKaze** [comment]
What command do I use ? I usually use "git pull"

On Sun, Apr 29, 2012 at 6:43 AM, avjui
reply@reply.github.com
wrote:

**Comment by KruyKaze** [comment]
Checked out Gametasks and i do not get that error anymore.
I do not have a NZB Matrix vip account bout use nzb.su , what port do
i use for that?
Thanks

**Comment by KruyKaze** [comment]
Here's what I get now:
Error getting game [PROTOTYPE 2] from Newznab   2012-04-29 13:02:17
DEBUG : Search for http://nzb.su/api?apikey=********************&t=search&cat=1050&q=PROTOTYPE+2&o=json 2012-04-29 13:02:17
Checking for game [PROTOTYPE 2] for [Xbox360] on Newznab    2012-04-29 13:02:16
Searching for game: PROTOTYPE 2 2012-04-29 13:02:16
Error getting game [Max Payne 3] from Newznab   2012-04-29 13:02:16
DEBUG : Search for http://nzb.su/api?apikey=******************************&t=search&cat=1050&q=Max+Payne+3&o=json   2012-04-29 13:02:16
Checking for game [Max Payne 3] for [Xbox360] on Newznab    2012-04-29 13:02:15
Searching for game: Max Payne 3 2012-04-29 13:02:15

**Comment by KruyKaze** [comment]
Also another error:
DEBUG : Check script_dir:
http://0.0.0.0:8092/sabnzbd/api?mode=get_config&apikey=*******************************f6e5§ion=misc&keyword=script_dir

**Comment by avjui** [comment]
You say the sabnzbd error is in The Gametasks branch not? That´s strange because i nothing do on the code only remove the "safe" of the code.
The thing with nzb.su i will test

By the way. The DEBUG messages are not errors they are only to check what the code do. So you can test it. For example take the 'http://0.0.0.0:8092/sabnzbd/api?mode=get_config&apikey=*******************************f6e5§ion=misc&keyword=script_dir' and test it in Browser.

**Comment by avjui** [comment]
Hi

They nzb.su iusses should be fixed. please can you check this.
For checkout  make 
git clone git@github.com:avjui/Gamez.git
than
cd Gamez
than
git checkout TheGamedb

Thanks for testing

**Comment by KruyKaze** [comment]
Ok did that . I get this :
Unable to connect to web service:
http://www.gamezapp.org/webservice/comingsoon   2012-04-29 22:17:35
Unable to connect to web service:
http://www.gamezapp.org/webservice/xbox360  2012-04-29 22:17:34
Unable to connect to web service:
http://www.gamezapp.org/webservice/wii  2012-04-29 22:17:34

also iI see : Searching for game: PROTOTYPE 2
But it's not downloaded.Although it is available :
http://www.abgx.net/filename/?ch=6

On Sun, Apr 29, 2012 at 12:17 PM, avjui
reply@reply.github.com
wrote:

**Comment by KruyKaze** [comment]
And later I got this output:
Error getting game [PROTOTYPE 2] from Newznab   2012-04-30 02:16:30
DEBUG : Search for http://nzb.su/api?apikey=**********************************&t=search&cat=1050&q=PROTOTYPE+2&o=json   2012-04-30 02:16:30
Checking for game [PROTOTYPE 2] for [Xbox360] on Newznab    2012-04-30 02:16:29
Searching for game: PROTOTYPE 2 2012-04-30 02:16:29
Setting permissions on post process script  2012-04-30 02:16:29
Copying post process script to Sabnzbd scripts folder   2012-04-30 02:16:29
Searching for games 2012-04-30 02:16:29

**Comment by avjui** [comment]
The webservice thing i know. Thats only for DB. But for nzb.su i added a new section in setting. Please try this one and disable newznab.

**Comment by avjui** [comment]
By the way is the error with 'Unable to connect to Sanzbd:' fixed? When yes and you have problem with nzb.su please make a new ticket

**Comment by KruyKaze** [comment]
Problem fixed!
Thanks.

On Mon, Apr 30, 2012 at 1:43 PM, avjui
reply@reply.github.com
wrote:
