### ISSUE TITLE
Create a Logo for Gamez

### ISSUE THREAD

**Issue by avjui** [avjui/Gamez#14]
Hi

Is there anybody how can creat a logo for Gamez. That would be nice.

**Comment by NielsLinders** [comment]
would a simple controller do? or did you have something else in mind?

**Comment by avjui** [comment]
What you think its good ;-)

**Comment by KruyKaze** [comment]
How about this one? http://cdn-img.easyicon.cn/png/5574/557413.gif

**Comment by KruyKaze** [comment]
And what are the requirements?

**Comment by avjui** [comment]
I don't know. The only thing for me is that I also become the same Picture as png with 16x16 for the icon in the browser ;-)

**Comment by KruyKaze** [comment]
http://i.imgur.com/lY8cN.png for a browser favicon

**Comment by avjui** [comment]
Thanks for your work. It is now in the git

**Comment by KruyKaze** [comment]
Thanks but I can't take credit. I had a friend make that icon :)
