### ISSUE TITLE
Auto update from Git

### ISSUE THREAD

**Issue by KruyKaze** [avjui/Gamez#15]
please add this feature.
Thank you.

**Comment by avjui** [comment]
This should be easy. I hope ;-)

**Comment by avjui** [comment]
Hi

I have change the code for this branch. So please update one more time to get the update function. 
;-)

**Comment by KruyKaze** [comment]
When i try git pull i get :

Updating b98bf46..a0564bc
error: Your local changes to the following files would be overwritten by merge:
    Gamez.ini
Please, commit your changes or stash them before you can merge.
Aborting

On Tue, May 1, 2012 at 7:54 AM, avjui
reply@reply.github.com
wrote:

**Comment by avjui** [comment]
Please move your Gamez.ini to a other folder then try again git pull.  This comes because you have change Gamez.ini

**Comment by KruyKaze** [comment]
Do I need to do this every time I update?
On May 1, 2012 11:16 PM, "avjui" <
reply@reply.github.com>
wrote:

**Comment by avjui** [comment]
No

**Comment by KruyKaze** [comment]
I updated but I don't see the feature.

**Comment by avjui** [comment]
Look at the commits and you will see that not every update you will see any new things because not any update bring new feature.

**Comment by KruyKaze** [comment]
Autoupdate works thanks
On May 3, 2012 10:37 AM, "avjui" <
reply@reply.github.com>
wrote:
