### ISSUE TITLE
Add XBMC Notification

### ISSUE THREAD

**Issue by smidley** [avjui/Gamez#16]
Can we get notifications in XBMC when a game download has started, and when it has finished?

**Comment by KruyKaze** [comment]
Would like that too.Or  a tweet would be fine too.

**Comment by avjui** [comment]
I have added the code so please test. You can notify more the one XBMC´s. for exanmple  use 192.174.1.12:80;192.174.1.24:8080

**Comment by KruyKaze** [comment]
Thanks
