### ISSUE TITLE
[Feature Request] - Add HTTPS Support

### ISSUE THREAD

**Issue by smidley** [avjui/Gamez#18]
SAB, Sickbeard, Couchpotato and other similar programs have HTTPS support, and this project needs it too.  :)

**Comment by avjui** [comment]
I have added some code please test.

**Comment by smidley** [comment]
I can't seem to get HTTPS to work.  Maybe I'm doing something wrong?  I enabled HTTPS and then changed my port to 9090.  I can access the program via HTTP, but when trying HTTPS I get page not found.

**Comment by avjui** [comment]
Perhaps you have forgotten to install openssl? When https support will be enabled first there will create to files in Gamez folder. One gamez.key and gamez.crt. When you don' t have this two files something went wrong with creating this file. Enable Debuglog for more information

**Comment by smidley** [comment]
I wasn't aware that I had to manually install OpenSSL first.  Here's my log.  http://pastebin.com/gFJefng0

Just states that it's unable to activate HTTPS support.  I never got the two files you were talking about either.  (gamez.key, an gamez.crt)

**Comment by avjui** [comment]
For Creating this files openssl is necessary. And for HTTPS support this files are necessary.

**Comment by smidley** [comment]
How come the same method that sab/sickbeard/couchpotato uses wasn't used?  Those don't require you to download anything, and they provide you with cert files.

**Comment by avjui** [comment]
That' s not right look at this code from sickbeard. 
https://github.com/brototyp/Sick-Beard/blob/some_providers/sickbeard/helpers.py
Line 543
There you also need openssl

**Comment by avjui** [comment]
Have you tested with openssl? Was this the solution for your problem

**Comment by smidley** [comment]
Haven't had a chance to test yet.  I will tomorrow morning though.

**Comment by avjui** [comment]
ok thanks

**Comment by smidley** [comment]
Manually installed Visual C++ 2008 and OpenSSL.  Still getting this error: !!!!!!!! Unable to activate HTTPS support !!!!!!!!!! Perhaps you have forgotten to install openssl?

I can access the program if I use HTTP still.

**Comment by smidley** [comment]
How come I can use Sabnzbd with HTTPS support on this computer without installing anything, but you're saying I need to manually install openssl for Gamez to work?

**Comment by avjui** [comment]
You only must install python openssl module from there https://launchpad.net/pyopenssl. Then all should be right.
Please test a second one. In the mean time I will have a look into the sources of sabnzbd.

**Comment by avjui** [comment]
Please look at the github page in the Readme for Dependencies. There also python openssl is needed https://github.com/sabnzbd/sabnzbd#resolving-dependencies.
Perhaps the exe file have the sources included.

**Comment by smidley** [comment]
I've manually downloaded the python OpenSSL and it's working now for me.  Is there any way that this dependency could be included and installed with Gamez?  I've just never had to manually look for and install additional components like this to make a related program work.
