### ISSUE TITLE
[Feature Request] Auto Search For Game Update

### ISSUE THREAD

**Issue by NielsLinders** [avjui/Gamez#20]
What would be really cool, if automatically search for game updates and downloaded them, so if lets say you were to add a game such as Battlefield 3 and it released an update on nzbmatrix, newzbin or a newzab site, it would automatically download it, so then you don't have to manually check when an update is available, this would also do the same thing for an DLC. It probably is an option you would want to set per game, as some games you may not want updates for.

**Comment by avjui** [comment]
At the moment I don´t plan to integrate this but patches are welcome.  ;-)
