### ISSUE TITLE
Gamez does not search periodically.

### ISSUE THREAD

**Issue by KruyKaze** [avjui/Gamez#21]
But it works when I force the search.
here's the output:

Major error occured when running scheduled tasks - - global name 'lib' is not defined -     2012-05-04 19:31:12

Thanks.

**Comment by avjui** [comment]
fix in git

**Comment by KruyKaze** [comment]
Thanks
On May 5, 2012 2:40 AM, "avjui" <
reply@reply.github.com>
wrote:
