### ISSUE TITLE
Search for added game immediately 

### ISSUE THREAD

**Issue by KruyKaze** [avjui/Gamez#22]
Check the game you just added to the wanted list to see if it's already out as soon as you add it.
Thanks

**Comment by avjui** [comment]
Please test code is in git

**Comment by KruyKaze** [comment]
No search when you add a game after update
On May 8, 2012 4:34 AM, "avjui" <
reply@reply.github.com>
wrote:

**Comment by avjui** [comment]
Please can you post me a debuglog. Here all is right

**Comment by KruyKaze** [comment]
I see no errors or searches:

DEBUG : TheGamesDB ID [None]    Wed 09 May 2012 / 00:32:49
Retrieving the latest version   Wed 09 May 2012 / 00:32:48
Checking to see if a new version is available   Wed 09 May 2012 / 00:32:48
Adding game in 'Wanted' status  Wed 09 May 2012 / 00:32:48

Thanks

On Tue, May 8, 2012 at 8:35 AM, avjui
reply@reply.github.com
wrote:

**Comment by avjui** [comment]
When you force search is then all right. Please can you have a look for you setting perhaps there something went wrong

**Comment by KruyKaze** [comment]
When I force search it works but I was asking to force search for the game
automatically when it's added.
Thanks
On May 9, 2012 2:49 AM, "avjui" <
reply@reply.github.com>
wrote:

**Comment by avjui** [comment]
I know what you mean and here it works. When you click 'Download' to the game what you have search for it makes a force Search for this Game.
When I have some time I added some DebugEvents to the code, then I hope we find the solution for the problem. Please stand by

**Comment by KruyKaze** [comment]
Ok thanks
On May 9, 2012 4:59 AM, "avjui" <
reply@reply.github.com>
wrote:

**Comment by avjui** [comment]
Please can you test the new update. I think i have found the solution.

**Comment by KruyKaze** [comment]
Hmm I was testing with one particular game and it didn't work but I tried with others and one of them worked.
I'm not sure why.

**Comment by avjui** [comment]
And when you force Search  for this games they don' t search immediately, did this work? Please can you post me the 'Debuglog' of adding and then a second for force when game was not search after adding

**Comment by KruyKaze** [comment]
If I force it works just fine. You want me to send another log for when I
add without forcing?
On May 9, 2012 11:15 PM, "avjui" <
reply@reply.github.com>
wrote:

**Comment by avjui** [comment]
Yes and then when you manual force this game

**Comment by KruyKaze** [comment]
Added "Men in Black" to test with right now. But the log is from 24 hours ago:
DEBUG : TheGamesDB ID [None]    Wed 09 May 2012 / 16:10:57
DEBUG : TheGamesDB ID [None]    Wed 09 May 2012 / 16:10:57
DEBUG : TheGamesDB ID [None]    Wed 09 May 2012 / 16:10:57
DEBUG : TheGamesDB ID [None]    Wed 09 May 2012 / 16:10:57
DEBUG : TheGamesDB ID [None]    Wed 09 May 2012 / 16:10:57
Retrieving the latest version   Wed 09 May 2012 / 16:10:56
Checking to see if a new version is available   Wed 09 May 2012 / 16:10:56

Today is thursday and time is 16:12

This is without forcing.

**Comment by KruyKaze** [comment]
Forced the search and waited a couple of more minutes.
No newer log entries

**Comment by avjui** [comment]
From where do you added this from upcoming games?

**Comment by KruyKaze** [comment]
yes

On Thu, May 10, 2012 at 11:12 PM, avjui
reply@reply.github.com
wrote:

**Comment by KruyKaze** [comment]
It seems to be working now thanks

**Comment by avjui** [comment]
Good then I close
