### ISSUE TITLE
Show local time in log

### ISSUE THREAD

**Issue by KruyKaze** [avjui/Gamez#23]
Thanks

**Comment by avjui** [comment]
What do you mean. On the right side there is time stamp of the entries

**Comment by KruyKaze** [comment]
I live in a different time zone than you, so my time shows wrong.

On Sat, May 5, 2012 at 11:27 AM, avjui
reply@reply.github.com
wrote:

**Comment by avjui** [comment]
fixed

**Comment by KruyKaze** [comment]
thanks

On Sat, May 5, 2012 at 4:43 PM, avjui
reply@reply.github.com
wrote:
