### ISSUE TITLE
Upcoming releases out of date

### ISSUE THREAD

**Issue by faintuk** [avjui/Gamez#24]
I've noticed this list doesn't include any pc/ps3 games

**Comment by avjui** [comment]
The Problem is i don´t know a web page where i can parse that information

**Comment by Markyb0y** [comment]
How about
http://www.gamerevolution.com/rss/release_dates.xml

the section is like this

```
<item>
<title>Carrier Command: Gaea Mission (Xbox 360)</title>
<description>Release date set for September 27, 2012.</description>
<link>http://www.gamerevolution.com/game/carrier-command-gaea-mission</link>
<enclosure url="http://media.gamerevolution.com/thumbnails/images/boxshots/carrier-command-gaea-mission.jpg" length="0" type="image/jpeg" />
<category>Xbox 360</category>
</item>
```

not sure how reliable it is but until thegamesdb api includes release dates?

**Comment by avjui** [comment]
I would have a look at that

**Comment by avjui** [comment]
Only notice for me

 http://www.gamerevolution.com/release.

**Comment by avjui** [comment]
Please test and report I have added some code
