### ISSUE TITLE
No new log entries ('clear Log' fix the problem)

### ISSUE THREAD

**Issue by KruyKaze** [avjui/Gamez#28]
My log is stuck at :   Wed 09 May 2012 / 16:10:47

**Comment by avjui** [comment]
Please can you test a fresh install from there https://github.com/avjui/Gamez/zipball/v1.1.16.18.
You can take the Gamez.db and Gamez.ini from your orignal and put it into the fresh install.

**Comment by KruyKaze** [comment]
I did exactly that and my log is still stuck at:
 DEBUG : TheGamesDB ID [None]   Wed 09 May 2012 / 16:10:57

On Fri, May 11, 2012 at 3:36 AM, avjui
reply@reply.github.com
wrote:

**Comment by avjui** [comment]
And when you press 'clear Log' in Log section. Perhabs you have to many entries.

**Comment by KruyKaze** [comment]
Yeah that was it. How about limiting the size of the log to eliminate this
problem?
On May 11, 2012 4:49 AM, "avjui" <
reply@reply.github.com>
wrote:

**Comment by avjui** [comment]
I have a look at this

**Comment by avjui** [comment]
Dirty fix .I have add a option how delete old entries at start

**Comment by KruyKaze** [comment]
i'll test it thanks

On Sat, May 12, 2012 at 3:03 PM, avjui
reply@reply.github.com
wrote:
