### ISSUE TITLE
gamezapp.org dead

### ISSUE THREAD

**Issue by akuiraz** [avjui/Gamez#29]
The Game list update button calls on the website gamezapp.org and since it's now dead, no upcoming games are ever populated

**Comment by avjui** [comment]
I know that the service is dead. At the moment I look for an alternate. Perhaps this http://www.gamerevolution.com/release/ps3 would be alternate. When anyone have a good site for  me with rss feeds please post it.

**Comment by smidley** [comment]
What about using http://www.thegamesdb.net ?

**Comment by avjui** [comment]
For DB update it is ok but for upcomming releases? Are there entrys for upcomming games?

**Comment by smidley** [comment]
When games are entered into our database, they get a date field put in.  I can create an API call that will show upcoming games based on that.

**Comment by pro2oman** [comment]
what about abgx.net ... it the actual scene names
also www.gametdb.com

**Comment by smidley** [comment]
We have a ticket opened for creating this API call.  https://github.com/TheGamesDB/TheGamesDB/issues/23

**Comment by avjui** [comment]
I will have a look at this when I have some time. It is on my todo.

@ smidley can you have some look on thegamesdb how much upcomming games there are. I don`t wont implement this when for ps3,xbox360 games there are only 10 entrys

**Comment by avjui** [comment]
Please Test and report I have update the code
