### ISSUE TITLE
[Feature Request] - Daemon Mode

### ISSUE THREAD

**Issue by smidley** [avjui/Gamez#30]
It would be nice to be able to daemonize Gamez so that we don't have to have a python command window open at all times, and the program can just keep running in the background.

**Comment by avjui** [comment]
There is a console option for this. Try to start with --daemonize.

**Comment by smidley** [comment]
When I use that console option, I see it stating "Preparing to run in daemon mode" and then the command window closes, but I can't see that Gamez is running as a process, and I can't access it via the Web GUI.

**Comment by avjui** [comment]
I will have a look at that

**Comment by smidley** [comment]
One way to get it to run "daemonized" in windows, is to launch it with pythonw.  But then you just get a process called pythonw running and you can't tell if it's Gamez or some other python thing you have running.

**Comment by avjui** [comment]
I have test it. In Linux it is alright do you run under windows?

**Comment by smidley** [comment]
Yes, I'm running on Windows Server 2008 R2.

**Comment by avjui** [comment]
The --daemoize option will not supported by windows. When I have time I will have a look to create a exe file. I hope this will fix the problem
