### ISSUE TITLE
Can't Search PC Games on NZBMatrix

### ISSUE THREAD

**Issue by smidley** [avjui/Gamez#31]
When looking for PC games on NZBMatrix, I get the following error:  Unrecognized System Wed 16 May 2012 / 13:06:27

**Comment by avjui** [comment]
I see the problem. I will fix it today. By the way games search for other sytems is ok?

**Comment by avjui** [comment]
Please test

**Comment by smidley** [comment]
Error getting game [****_] from NZB Matrix  Thu 17 May 2012 / 01:44:40
Checking for game [**_**\* on NZB Matrix Thu 17 May 2012 / 01:44:40
Searching for game: *****\*  Thu 17 May 2012 / 01:44:40

**Comment by avjui** [comment]
The problem is that i don' t have a vip account of nzbmatrix. So I can' t test it. Please can you post me the output when you put the search url direct in browser.
In Debug mode you will see the search url

**Comment by smidley** [comment]
Here's what happens when I try to download one that I know has been released

Gamez Output:
Error getting game [Fake Game Name] from NZB Matrix Thu 17 May 2012 / 02:52:36
DEBUG : Search URL [ http://api.nzbmatrix.com/v1.1/search.php?search=Fake Game Name&num=1&catid=10&username=****_&apikey=**_***************\* ]  Thu 17 May 2012 / 02:52:35

I blocked out my username and API key, and changed the name of the game to "Fake Game Name".

Here's what it says when I use that URL in a browser:
NZBID:1279219; NZBNAME:Fake Game Name; LINK:nzbmatrix.com/nzb-details.php?id=1279219&hit=1; SIZE:16599073423.4; INDEX_DATE:2012-05-17 00:03:32; USENET_DATE:2012-05-17 12:04:51; CATEGORY:Games > PC; GROUP:alt.binaries.games.pc; COMMENTS:0; HITS:0; NFO:yes; WEBLINK:http://en.wikipedia.org/wiki/Fake_Game_Name; LANGUAGE:English; IMAGE:http://img444.imageshack.us/img444/3122/fakegamename.png; REGION:0; |

**Comment by avjui** [comment]
Have make some change. Please test

**Comment by smidley** [comment]
Still get the same error.

Error getting game [Fake Game Name] from NZB Matrix
However, that's when I search for a game that isn't available on NZBMatrix yet.

When looking for a game that is actually on the site, I get this:

Game found on NZB Matrix    Thu 17 May 2012 / 10:42:38
DEBUG : Additions for Fake Game Name are    Thu 17 May 2012 / 10:42:38
DEBUG : Search URL [ http://api.nzbmatrix.com/v1.1/search.php?search=Fake Game Name&num=1&catid=10&username=****_&apikey=**_*************\* ]    Thu 17 May 2012 / 10:42:37
DEBUG : Here i am   Thu 17 May 2012 / 10:42:37
Checking for game [Fake Game Name] on NZB Matrix    Thu 17 May 2012 / 10:42:37

The Game never gets downloaded even though it's found on NZBMatrix and on NZB.su.

**Comment by avjui** [comment]
The first thing it' s not a bug but i add some code for better problem hunting. And the second output looks good but he don' t try to send anything to sab. Are the settings right? When you start up gamez you will see that gamez copy a script to sab script folder. When this is alright than the settings seems to be right.

**Comment by smidley** [comment]
Seems my settings may have been wrong for sab.  Although, I just fixed them and restarted gamez, but now gamez isn't working.  I'll investigate.

**Comment by avjui** [comment]
Can you find the solution for your problem?

**Comment by smidley** [comment]
All appears to be working now
