### ISSUE TITLE
Won't snatch?

### ISSUE THREAD

**Issue by faintuk** [avjui/Gamez#32]
I've Started to get the following error when searching for games

DEBUG : TheGamesDB ID [None]    Wed 16 May 2012 / 22:36:55
DEBUG : TheGamesDB ID [8874]    Wed 16 May 2012 / 22:36:55
DEBUG : TheGamesDB ID [36]  Wed 16 May 2012 / 22:36:55
DEBUG : TheGamesDB ID [None]    Wed 16 May 2012 / 22:36:55
DEBUG : TheGamesDB ID [None]    Wed 16 May 2012 / 22:36:54
DEBUG : TheGamesDB ID [8912]    Wed 16 May 2012 / 22:36:54
DEBUG : TheGamesDB ID [8170]    Wed 16 May 2012 / 22:36:54
Retrieving the latest version   Wed 16 May 2012 / 22:36:53
Checking to see if a new version is available   Wed 16 May 2012 / 22:36:53
DEBUG : Torrent Enable  Wed 16 May 2012 / 22:36:53
Error getting game [Gears of War 3] from NZB Matrix Wed 16 May 2012 / 22:36:53
DEBUG : Search URL [ http://api.nzbmatrix.com/v1.1/search.php?search=Gears of War 3&num=1&catid=14&username=xxx&apikey=xxx ]    Wed 16 May 2012 / 22:36:52
DEBUG : Here i am   Wed 16 May 2012 / 22:36:52
Checking for game [Gears of War 3] on NZB Matrix    Wed 16 May 2012 / 22:36:52
DEBUG : Matrix Enable   Wed 16 May 2012 / 22:36:52
Searching for game: Gears of War 3  Wed 16 May 2012 / 22:36:52
Unable to copy post process script to Sab folder    Wed 16 May 2012 / 22:36:52
Copying post process script to Sabnzbd scripts folder   Wed 16 May 2012 / 22:36:52
Searching for games Wed 16 May 2012 / 22:36:51

Any ideas?

**Comment by avjui** [comment]
The problem is that i don' t have a vip account of nzbmatrix. So I can'  t test it. Please can you post me the output when you put the search url direct in browser.

**Comment by faintuk** [comment]
Seems updating to the latest version fixed it
