### ISSUE TITLE
Bug getting download directory from SABNZBD+ Win7 64b

### ISSUE THREAD

**Issue by Elroban** [avjui/Gamez#34]
My default download directory for SABNZBD+ is 
D:\Download\Complete\
MY default download directory for SABNZBD+ category games (used for Gamez) is
D:\Download\Complete\Games

When starting Gamez, he tries to retrieve the download dir from Sabnzbd.
This results in saving the value 
D

Nothing more so it seems it can't cope with the ':' or the single '\'

**Comment by Elroban** [comment]
This might also be the reason why the postprocess script can't be copied.

Date / Time
Unable to copy post process script to Sab folder    Fri 25 May 2012 / 13:38:38
Copying post process script to Sabnzbd scripts folder   Fri 25 May 2012 / 13:38:38
Setting permissions on post process script  Fri 25 May 2012 / 13:38:38
Generating Post Process Script  Fri 25 May 2012 / 13:38:38

**Comment by avjui** [comment]
When I have time I will have a look at this.

**Comment by avjui** [comment]
Please can you test. I have made a change in git

**Comment by Elroban** [comment]
With the newest version both my Sabnzbd+ folder as the copying of the post process script works perfect.
Issue solved, thanks
