### ISSUE TITLE
cant access outside of local host

### ISSUE THREAD

**Issue by pro2oman** [avjui/Gamez#37]
works fine when im the server itself.. but not when trying from another computer on the network. ports HAVE been forwarded.
without access from another computer running it on a headless server is pointless.

**Comment by avjui** [comment]
Your Gamze Host settings must be 0.0.0.0 for getting accses from everywhere. Please check this setting.

**Comment by pro2oman** [comment]
wow.. that was stupid of my.. i had tried both 127.0.0.1 and local host but not 0.0.0.0 .. shouldn't that be the default setting?
