### ISSUE TITLE
unknow system

### ISSUE THREAD

**Issue by pro2oman** [avjui/Gamez#38]
when adding a game that's not in the db but found on thegamesdb.com , at least for wii games it doesn't recognize the system.

"ERROR: No System foundNintendo Wii" 
for example pikmin 2

also after you delete and re-adding a game to wanted list.. it now shows up multiple times when you type it in the search

edit: also cant find "New Play Control! Pikmin" but if it searched pikmin it would.. possible option for manual search when not found? or renaming the game.

**Comment by avjui** [comment]
Is fixed.
