### ISSUE TITLE
Cant seem to get this working on OSX

### ISSUE THREAD

**Issue by mew0717** [avjui/Gamez#39]
When running i get the following error:  Could it be something i'm doing wrong.   Sickbeard, sab, cp and headphones all work fine on this machine.

Traceback (most recent call last):
  File "Gamez.py", line 5, in <module>
    from gamez.WebRoot import WebRoot
  File "/Applications/avjui-Gamez-b9ac4b9/gamez/WebRoot.py", line 15, in <module>
    from GameTasks import *
  File "/Applications/avjui-Gamez-b9ac4b9/gamez/GameTasks.py", line 12, in <module>
    from Helper import replace_all,FindAddition
  File "/Applications/avjui-Gamez-b9ac4b9/gamez/Helper.py", line 31
    dic = {'PAL', 'USA', 'NSTC', 'JAP', 'Region Free', 'RF', 'FRENCH', 'ITALIAN', 'GERMAN', 'SPANISH', 'ASIA', 'JTAG', 'XGD3', 'WiiWare', 'WiiVC', 'Mixed'}
                ^
SyntaxError: invalid syntax

**Comment by avjui** [comment]
Hi

I don´t see a problem. Do you get this error at start or when you are searching?.

**Comment by mew0717** [comment]
When i try to run this in terminal to start it up, i get that error.

On Mon, Jun 18, 2012 at 12:33 AM, avjui <
reply@reply.github.com

**Comment by avjui** [comment]
Which python Version do you have?

**Comment by Bart39** [comment]
i have the same issue on debian using python 2.6.6

**Comment by avjui** [comment]
Here I have tested with freenas, ubuntu and windows and I don´t have a problem. Please can you update python to 2.7

**Comment by mew0717** [comment]
Upgrading to 2.7 did the trick.

Thank you!

On Tue, Jun 19, 2012 at 12:45 PM, avjui <
reply@reply.github.com
