### ISSUE TITLE
Not searching

### ISSUE THREAD

**Issue by alistairgore** [avjui/Gamez#40]
This is the log file, I have added a game to the list that is in NzbMatrix.  But it wont sent it to sabnzbd

Retrieving the latest version   Sun 17 Jun 2012 / 10:32:41
Checking to see if a new version is available   Sun 17 Jun 2012 / 10:32:41
Unrecognized System Sun 17 Jun 2012 / 10:32:39
Checking for game [Crackdown] on NZB Matrix Sun 17 Jun 2012 / 10:32:39
Searching for game: Crackdown   Sun 17 Jun 2012 / 10:32:39
Setting permissions on post process script  Sun 17 Jun 2012 / 10:32:39
Copying post process script to Sabnzbd scripts folder   Sun 17 Jun 2012 / 10:32:39
Searching for games Sun 17 Jun 2012 / 10:32:39
Retrieving the latest version   Sun 17 Jun 2012 / 10:32:31
Checking to see if a new version is available

**Comment by avjui** [comment]
Please enable Debuglog for more information.

**Comment by alistairgore** [comment]
Ok I've enabled debug does it store a log file somewhere

**Comment by avjui** [comment]
At the moment the entry's are in the Gamez.db file. You need a sql browser to look in the file

**Comment by avjui** [comment]
Dose you found the reason or is the bug still alive?
