### ISSUE TITLE
Default Script for Selected Category not executed

### ISSUE THREAD

**Issue by BrandonG777** [avjui/Gamez#43]
I have a post processing script that is supposed to run after items are downloaded within my console category but items downloaded using Gamez are not executing that script.

**Comment by avjui** [comment]
Hallo

I think the problem is that Gamez has his own post processing script (for status of the game) and I am not sure that sabnzbd can handel multiple post processing script.  
Perhaps I can make a option to deactivate this. Do you think that would help?

**Comment by BrandonG777** [comment]
Perhaps integrating my abgx360 script would be an option?

http://forums.sabnzbd.org/viewtopic.php?f=9&t=1735&p=10752#p10752

**Comment by avjui** [comment]
What dose the script exactly? Dose it make a twitter? So your really feature request would be a twitter support?

**Comment by BrandonG777** [comment]
No the twitter stuff can be omitted I don't use that portion of the script anymore. abgx360 checks the validity of 360 ISO images to make sure they pass Stealth & AP25 checks, and autofixes problems if possible. Anyone downloading 360 ISOs should be using it unless they have a JTAG box.

**Comment by avjui** [comment]
So when i understand this right every iso would be check from this program and will it autofixe when some problems are. Is this right?
Perhaps I can include the check for XBOX Games

**Comment by BrandonG777** [comment]
Yes every XBOX360 ISO should be checked but JTAG users don't need to check so a switch in settings would be good.

**Comment by avjui** [comment]
I close hier and make a new feature Request

**Comment by avjui** [comment]
Hi

You can test this branch https://github.com/avjui/Gamez/tree/developer.
Here games will be renamed, removed and write a NFO file. In this version Gamez not need a postprocessing script so you can add yours for xbox360.  Notice!! Please make no update over webif because it will update to main branch
