### ISSUE TITLE
[Feature request] Integrate Notify My Android support

### ISSUE THREAD

**Issue by martynvs** [avjui/Gamez#46]
Could you integrate support for Notify My Android (NMA) support like in SickBeard has? https://github.com/midgetspy/Sick-Beard/blob/master/sickbeard/notifiers/nma.py

**Comment by avjui** [comment]
I will have a look at this but at the moment i don't have much time.

**Comment by aaronflorey** [comment]
I coded in support for this, and it has been added into the main repo :3
