### ISSUE TITLE
Tidy up CSS

### ISSUE THREAD

**Issue by Markyb0y** [avjui/Gamez#48]
Hi,

in an effort to standardise the look and feel of Gamez so it is more similar to headphones and couchpotato for example, they use a width of 960px centred.

i have made the following changes to the CSS of the default and grey themes to get this required result. it does mean that I have to make these changes each time I update, so I am hoping you will agree this makes a better looking app and adopt these new settings within the source code for all to use in future releases, 3 files need to be changed

navigation.css
change width to 960px, the auto margins set it to centered

div#menu {
    height:41px;
    width: 960px;
    margin-left: auto;
    margin-right: auto;
    background:url(navigation_images/main-bg-grey.png) repeat-x;
}

datatables.css
change width to 960 px
# dt_example #container {

```
width: 960px;
margin: 30px auto;
padding: 0;
```

}

jquery.ui.override.css
set search bar to 185px to fit the available space

input.ui-autocomplete-input
{
    width:185px
}

I would also make the suggestion that the wanted, snatched and downloaded dropdowns go below the logo link so the home (text)link can be removed, update game list and the shutdown and reboot links go under Settings removing the need for the power icon, and reordering the links to a more user friendly list, HOME | UPCOMING RELEASES | LOG | SETTINGS

you can make this change in webroot.py (it appears 5 times on this file so need to change all of them)

```
            <ul class="menu">
                <li class="parent">
                    <a href="/"><img src="images/gamezlogo.png" height="41" alt="Gamez"></a>
                    <ul><li><a href="/?filter=Wanted">Wanted Games</a></li><li><a href="/?filter=Snatched">Snatched Games</a></li><li><a href="/?filter=Downloaded">Downloaded Games</a></li></ul>
                </li>
                <li class="parent">
                    <a href="/comingsoon">
                        Upcoming Releases
                    </a>
                </li>
                <li class="parent">
                    <a href="/log">
                        Log
                    </a>
                </li>
                <li class="parent">
                    <a href="/settings">
                        Settings
                    </a>
                    <ul><li><a href="/updategamelist">Update Game List</a></li><li><a href="/reboot">Reboot</a></li><li><a href="/shutdown">Shutdown</a></li></ul>
                </li>
            </ul>
```

thanks

Markyb0y

**Comment by avjui** [comment]
Hi

First Thanks for your work. I don´t understand much from html and css so I am lucky that somebody has a look at that.
It would be great if you would make a fork and make your changes and send me a pull request. Than I think we could implement this easy.
What do you think about the idea that you can support the themes? I think that there are more then one bug´s. :-)

**Comment by Markyb0y** [comment]
ok after looking at the styling there is an issue or two, due to the fact that there is no template system in Gamez, all changes would need to be made in the main webroot.py file, this would mean changing the existing themes, even theme selection is done by manual coding on the same webroot.py file.

I was hoping to be able to just create a new css folder but it simply wont work like that beyond very simple changes.
Therefore I would suggest I begin looking at converting the current application to use a templating system, I must point out that I am new to Python and I have never done anything like this but I am willing to put in some hours to get it done. My background is website design (CSS HTML etc.)

the reason I am pointing this out here is that I don't want to start making any changes to main files that others are changing also so what new features/styles etc are you working on currently? I saw you are looking to integrate abgx360 in post processing (which would be awesome), I also assume this wouldnt have much effect on the existing setup and any new code could be integrated at a later date.

what do you think?

**Comment by Markyb0y** [comment]
avjui, I cannot work out how to commit my changed WebRoot.py file, here are the steps I am taking
1. fork https://github.com/avjui/Gamez
2. git clone https://github.com/Markyb0y/Gamez.git
3. cd Gamez
4. git remote add upstream https://github.com/avjui/Gamez.git
5. git fetch upstream
6. make changes to WebRoot.py
7. git status (shows Changes not staged for commit:, modified:   gamez/WebRoot.py)
8. git add gamez/WebRoot.py
9. git status (shows Changes to be committed:, modified:   gamez/WebRoot.py)
10. git commit -m "Reorder the menu" gamez/WebRoot.py

[TheGamedb c0f60a5] Reorder the menu
 1 file changed, 70 insertions(+), 131 deletions(-)

now what?

I dont see the update in my files on github or in my commits on github?
I assumed I would see the new file then be able to send a pull request to you?

**Comment by avjui** [comment]
First my change are all in the Thegamedb branch. To bring your change up to git you must "git push"
