### ISSUE TITLE
A new API call has been created for thegamesdb - List all games for a platform

### ISSUE THREAD

**Issue by smidley** [avjui/Gamez#5]
You can now list all games for a certain platform via the API.  Here is an example:

http://thegamesdb.net/api/PlatformGames.php?platform=microsoft+xbox+360

This will return the game Title, Release Date, and Front box cover thumbnail image.

You can also get a listing of available platforms by performing the following call:

http://thegamesdb.net/api/GetPlatformsList.php

**Comment by avjui** [comment]
Thanks, I will have a look at this at next day´s. This i a good thing for update local DB

**Comment by smidley** [comment]
It seems like a better option for this program would be to just query thegamesdb for info when a search is performed or when a game title is requested by the program.  Instead of creating a local database and relying on that.  This way you wouldn't always have to manually update your local copy whenever a new game comes out.

**Comment by avjui** [comment]
I think you are right. I will have a look at the search field perhaps I can implant a 'realtime' Search for TheGamesDB.net
