### ISSUE TITLE
[Feature request] Add support for datadir

### ISSUE THREAD

**Issue by ChronoStriker1** [avjui/Gamez#50]
Using unraid for my server I would like to have the application in memory and the config data in a directory that is written to a harddrive.  It is a setting in headphones, I was wondering if the functionality can be added here.

**Comment by avjui** [comment]
I will have a look at that, but at the moment i don't have any time. Patches are welcome. ;-)

**Comment by avjui** [comment]
So its done I hope. Please can you test it it is in a new branch "Configpath" see here.
https://github.com/avjui/Gamez/tree/Configpath

Please give me feedback

P.s.: Please ignore update when you test

**Comment by ChronoStriker1** [comment]
For all intents and purposes it looks like its running, but I am having the same issue that the last person in the sabnzbd thread seems to be having. Also I believe I am running python 2.6.6 since you asked him and he never responded.

**Comment by avjui** [comment]
Please try to update to 2.7

**Comment by ChronoStriker1** [comment]
Due to the restrictions I have with the other software on my unraid machine, which all use the same python build, I cant update to 2.7

**Comment by avjui** [comment]
The problem is that you need Python 2.7+ or 3.0+ to use dict/set comprehensions

**Comment by avjui** [comment]
So I have made a change that ,I hope, fix your problem. Please can you checkout https://github.com/avjui/Gamez/tree/Configpath for testing. And no update please from webinterface.

**Comment by ChronoStriker1** [comment]
Just tried it and got this error on start

Traceback (most recent call last):
  File "/usr/local/gamez/Gamez.py", line 353, in <module>
    RunApp().RunWebServer()
  File "/usr/local/gamez/Gamez.py", line 37, in RunWebServer
    css_webinterface = "css/" + config.get('SystemGenerated','webinterface').replace('"','')
  File "/usr/lib/python2.6/ConfigParser.py", line 311, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'SystemGenerated'

**Comment by avjui** [comment]
It seems that the --config option make a proplem. I will have a look at that tomorrow. How do you start Gamez?

**Comment by avjui** [comment]
Please checkout and test one more. I hope i have fix it ;-)

**Comment by ChronoStriker1** [comment]
Getting this error

Traceback (most recent call last):
  File "gamez/Gamez.py", line 353, in <module>
    RunApp().RunWebServer()
  File "gamez/Gamez.py", line 99, in RunWebServer
    GenerateSabPostProcessScript()
  File "gamez/Gamez.py", line 137, in GenerateSabPostProcessScript
    file = open(postProcessScript,'w')
IOError: [Errno 2] No such file or directory: '/usr/local/postprocess/gamezPostP                                                                                                                                                                                                                                             rocess.py'

My current path for that folder would be /usr/local/gamez/postprocess/gamezPostProcess.py

**Comment by avjui** [comment]
How do you start Gamez? I don´t can reproduce your error. I have test it with python 2.6.6 on my windows maschine and I don´t see an error.
Do you start Gamez inside the root path of Gamez?

For example the new options are  

config=/usr/local/config/Gamez.in 
datadir=/usr/local/datadir/

**Comment by ChronoStriker1** [comment]
Normally I don't start inside the root path, starting it from there, works correctly.

**Comment by ChronoStriker1** [comment]
normally it would be started with this command

sudo -u nobody python /usr/local/gamez/Gamez.py -d --port 8089---datadir /mnt/cache/.gamez --nolaunch --pidfile /var/run/gamez/gamez-8089.pid"

and that would be in / run as root
its part of a startup script that automatically would install and start the program

**Comment by avjui** [comment]
Thats the problem. The code is made for starting at root path. Please create a new ticket if this is a problem for you.
The config and datadir option works correctly for you?

**Comment by ChronoStriker1** [comment]
They do appear to, but since gamezapp seems to be down, I cant do much actual testing.  Its starting and it looks like the config is setting.

**Comment by avjui** [comment]
Ok i will merge this change in to the main line. I will have also a look at the problem with start outsite the root path, but please can you make a new issues for this. Thanks

**Comment by ChronoStriker1** [comment]
Thanks and done!
