### ISSUE TITLE
launches webbrowser but no server started

### ISSUE THREAD

**Issue by creche** [avjui/Gamez#52]
After launching the script for the first time nothing happens.  When I try to run the setup.py I get an error about pyexe, maybe due to the fact that I am not running windows.

Hans-2:~ hans$ python /Gamez/Gamez.py -d
------------------- Preparing to run in daemon mode -------------------
------------------- launch Browser ( 0.0.0.0:8888) -------------------

Python 2.7 (r27:82508, Jul  3 2010, 20:17:05) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin

[global]
server.socket_host = "0.0.0.0"
gamez_port = 8888
user_name = 
password = 
debug_enabled = YES

**Comment by avjui** [comment]
First why do you need setup.py? 

And second please start games inside the folder

try:
Hans-2:~ hans/Gamez$ python Gamez.py -d

Have you Gamez on the same machine with you want launch in Web interface or a different?

**Comment by creche** [comment]
After failing to run the script, I ran the setup to see if that needed to be run.

Gamez is in a folder on the root of the drive.  I can run sickbeard/couchpotato/headphones all fine, on different ports of course.

**Comment by avjui** [comment]
Have you tested to start Gamez from "Gamez root dir "? Please try to run without -d for test and post console log.

try:

 Hans-2:~ hans/Gamez$ python Gamez.py

**Comment by creche** [comment]
Hans-2:~ hans$ cd /Gamez/
Hans-2:Gamez hans$ python gamez.py
------------------- launch Browser ( 0.0.0.0:8888) -------------------

Does not make a difference.  Is there a verbose flag to have it output more info? Where is the log file stored?

**Comment by avjui** [comment]
With python version do you use? 
On witch system do you run Gamez ?

Please delete Gamez.ini and start again. I don´t know what you problem is.

**Comment by creche** [comment]
2.7

It is run on a PowerMac G5 running 10.5.8
I can try running it on an Intel Mac in the office.

**Comment by creche** [comment]
Works on an iMac running 10.7.5.  No other script has issues with my PowerMac, so it is strange this one does.

**Comment by avjui** [comment]
Sorry but I don´t can help you with mac issues. I don´t have any mac here. When you find the problem please say me the fix for it.

**Comment by creche** [comment]
I see the problem.  The script creates a db and an ini file in the directory it is launched from not the directory where the python script resides.

When launching from ~/Gamez/Gamez.py it creates the ini in the ~/ folder.  

If you look at couchpotato.py (https://github.com/RuudBurger/CouchPotato/blob/master/CouchPotato.py) it defines a datadir, maybe that would fix it?

**Comment by avjui** [comment]
Please can you checkout the Configpath branch for testing. This branch contains the datadir and config option.

For example: python Ganze.py datadir=/home/

And please always start from Gamez root path.

**Comment by avjui** [comment]
Have make some update in the Configpath branch. Please test one more time.

**Comment by creche** [comment]
That new version launches ok, but anytime I have to restart it crashes.

[13/Oct/2012:18:30:16] ENGINE Re-spawning Gamez.py
Traceback (most recent call last):
  File "Gamez.py", line 353, in <module>
    RunApp().RunWebServer()
  File "Gamez.py", line 121, in RunWebServer
    cherrypy.engine.block()
  File "/gamez/cherrypy/process/wspbus.py", line 332, in block
    self._do_execv()
  File "/gamez/cherrypy/process/wspbus.py", line 379, in _do_execv
    os.execv(sys.executable, args)
OSError: [Errno 45] Operation not supported

**Comment by avjui** [comment]
Please can you test this Gamez.py http://pastebin.com/hxj0D7jE an report. It seems that OSX has problem with autoreload.

**Comment by creche** [comment]
That seems to be stable.  Thank you for all your effort.

**Comment by avjui** [comment]
Please can you test one more. I have make a check for darwin. Here is the new Gamez.py http://pastebin.com/1GqFnYgD
