### ISSUE TITLE
[Feature request] - Ability to start program from a path other then the app root

### ISSUE THREAD

**Issue by ChronoStriker1** [avjui/Gamez#53]
normally it would be started with this command

sudo -u nobody python /usr/local/gamez/Gamez.py -d --port 8089---datadir /mnt/cache/.gamez --nolaunch --pidfile /var/run/gamez/gamez-8089.pid"

and that would be in / run as root

**Comment by avjui** [comment]
Please checkout Configpath branch for testing.

**Comment by avjui** [comment]
Have make some update please test one more time

**Comment by ChronoStriker1** [comment]
Ignore this, used wrong branch

**Comment by ChronoStriker1** [comment]
It seems to be working as expected :)

**Comment by avjui** [comment]
When i have time today i will push the changegs into main line. Thanks for testing
