### ISSUE TITLE
Not working for me...

### ISSUE THREAD

**Issue by alittlerusty** [avjui/Gamez#56]
Trying to set this up on a windows box with python 2.7.3 installed.
I have Sabnzbd setup and working correctly with couchpotato and sickbeard, also have nzbmatrix vip account enabled, log file with debug enabled below:

DEBUG : TheGamesDB ID [None]                            Thu 18 Oct 2012 / 23:55:5
DEBUG : TheGamesDB ID [None]                            Thu 18 Oct 2012 / 23:55:55
DEBUG : TheGamesDB ID [None]                            Thu 18 Oct 2012 / 23:55:55
DEBUG : TheGamesDB ID [None]                            Thu 18 Oct 2012 / 23:55:55
Retrieving the latest version                                           Thu 18 Oct 2012 / 23:55:52
Checking to see if a new version is available                                      Thu 18 Oct 2012 / 23:55:52
Starting the Gamez web server                                              Thu 18 Oct 2012 / 23:55:47
Setting up folder processing scheduler                                     Thu 18 Oct 2012 / 23:55:47
Setting up game list update scheduler                                       Thu 18 Oct 2012 / 23:55:47
Setting up download scheduler                                           Thu 18 Oct 2012 / 23:55:47
Getting download interval from config file and invoking scheduler       Thu 18 Oct 2012 / 23:55:47
Searching for game: New Super Mario Bros. Wii                           Thu 18 Oct 2012 / 23:55:47
Searching for game: Lego Star Wars: The Complete Saga               Thu 18 Oct 2012 / 23:55:47
Searching for game: LEGO Batman: The Videogame                  Thu 18 Oct 2012 / 23:55:47
Searching for game: Donkey Kong Country Returns                 Thu 18 Oct 2012 / 23:55:47
Unable to connect to Sanzbd: http://127.0.0.1:8085/sabnzbd/api?mode=get_config&apikey=5xxxxxxxxxxxxxxxxxxxxxxxxxd5§ion=misc&keyword=script_dir 
                                                                                Thu 18 Oct 2012 / 23:55:47
Searching for games                                                             Thu 18 Oct 2012 / 23:55:47
Setting permissions on post process script                  Thu 18 Oct 2012 / 23:55:47
Generating Post Process Script                          Thu 18 Oct 2012 / 23:55:47
Generating CherryPy configuration                       Thu 18 Oct 2012 / 23:55:47

When I put the error url above directly into a  browser I get 'error: API key incorrect' (or words to that effect), however this throws an error warning in Sabnzbd saying that the apikey is incorrect whilst when running through gamez doesn't show any error warning in Sabnzbd. I know that the apikey I have entered is correct as the same one works perfectly for sickbeard and couchpotato. I note that there is no "&" at the end of the apikey, but am not familar with sabnzbd api to say if this is correct or not. Any ideas?

**Comment by avjui** [comment]
It seems that the api key will not be right encode. The right line must be
http://127.0.0.1:8085/sabnzbd/apimode=get_config&apikey=5xxxxxxxxxxxxxxxxxxxxxxxxx&section=misc&keyword=script_dir 
Please can you post the last 3 numbers of your api key.  I will have a look when I have time

**Comment by alittlerusty** [comment]
Last three digits of current api key = 5d5, but I have tried a different one, last three digits = 3f2 which also did not work. 
Not sure what way gamez is built, does it look directly for the nzb's on nzbmatrix first and then pass them to sabnzbd? just wondering as I don't see anything in the log about successful connection to nzbmatrix?

Thanks.

**Comment by avjui** [comment]
What system do you look for?

**Comment by alittlerusty** [comment]
not sure if I understand what you are asking, if what games console then it is for wii, I have checked and can pull down some of the games I requested manually from nzbmatrix.

**Comment by avjui** [comment]
What happens when you "force search". Can you post your config please (Gamez.ini). Have you take the exe or are you take the git?

**Comment by alittlerusty** [comment]
ok, I'm not at home at moment so will post config later, os is whs2011 and python 2.7.3

**Comment by avjui** [comment]
Git or exe?

**Comment by alittlerusty** [comment]
I downloaded the zip from the download link https://github.com/avjui/Gamez/downloads and run by calling gamez.py in a .bat

**Comment by alittlerusty** [comment]
Force search also did not work, can't remeber what the log said, I will paste the log from this when I get home also.

**Comment by avjui** [comment]
Perhaps the exe have some problem. Please can you try git (tag) and start with python Gamez.py from a comandoline

**Comment by alittlerusty** [comment]
tried latest version from tags,  v1.1.17.1.zip  b19c4376e5 · Uploaded October 15, 2012, started from comandline,still the same error, see http://pastebin.com/vWwd9hMCee for error log.
gamez.ini file is here http://pastebin.com/F43GyQrv

**Comment by avjui** [comment]
Please can you checkout new tag 1.1.17.2. I think it will fix the problem with search on NZBMatrix report if there any problems with send to sabnzbd.

**Comment by alittlerusty** [comment]
Installed 1.1.17.2, Nzbmatrix appears to be grabbing nzb but still has a problem connecting to sabnzbd. Log is here: http://pastebin.com/ys1AkGim
FYI no warnings flagged in Sabnzbd either.

**Comment by avjui** [comment]
When you put the line into browser something happen? I don't see any problem here and the log seems to be ok for sending. Later i will test on windows 7. Maybe you can test to put localhost or the real ip instant 127.0.0.1. 
Wich version of sabnzbd do you use?

**Comment by avjui** [comment]
Hi

I have tested newest version here on Windows 7 and I don´t can see any problem. The only thing I can confirm is the problem with getting the download path but this will be obsolete in the next future because the postprocessing I will rework. The only idea I have is that something in your config maybe is not right. Please test to put the line into the browser and look what you must change that sabnzb answer.

**Comment by alittlerusty** [comment]
You are correct, I hadn't much time yesterday and forgot to change the sabnzbd port setting for the latest version, with this fixed it has now snatched the nzb and sent them to sabnzbd which is currently downloading them, so all looks to be working!! Excellent stuff, really appreciate all your effort getting this sorted.
