### ISSUE TITLE
PS3 searching games dont work :( for All games

### ISSUE THREAD

**Issue by piotrasd** [avjui/Gamez#57]
Hi
I have latest developer version but i saw the searching engine dont work for all games

Like example: Cars 

i get alwayes info No Results Found. Try Searching Again

But game exist :/, even few titles:
Cars, Cars 2, Cars: Race O Rama

Or can,t to find

Medal Of Honor Warfighter

**Comment by avjui** [comment]
Please can you enable debuglog and post what he said. What os do you have? Wich provider do you use for search?

**Comment by avjui** [comment]
Hmm You must also look that thegamesdb.net contains the ps3 game. When it dose not exit there you don't can add it. Please add Game to TheGamesDB.net
