### ISSUE TITLE
Add support for other systems (ROMS)

### ISSUE THREAD

**Issue by smidley** [avjui/Gamez#64]
I would like to be able to use this program to get games for older platforms as well.  This would be things like roms for nintendo, super nintendo, sega genesis, etc.

**Comment by avjui** [comment]
I don´t think it makes sense because when I download roms most of  them I get in a "package". The next thing is that the nzbindex sites do not have specific categorys for this roms.

**Comment by smidley** [comment]
How about the ability to download rom sets?  These could be searched just by their platform titles and then provide you with a results list of ones available.

**Comment by avjui** [comment]
For the moment I have other things with higher priority. So I will set this on my TODO and close this ticked for the moment.
