### ISSUE TITLE
Postproccess will not work

### ISSUE THREAD

**Issue by avjui** [avjui/Gamez#65]
Have you on special postprocess script in SABnzbd how change the foldername of the game?
Have you set the SABnzbd completed order and activate postprocessing for XBOX360 games in settings?

The postprocessing thread will looking for the game in this structur:  
[completet-folder-sabnzbd] / [gamename (system)]

Please note that the completet folder name not end wich slash or backslach

**Comment by aaronflorey** [comment]
gamez\Call of Duty- Black Ops II  (Xbox360)

Checking Folder for postprocessing  Thu 15 Nov 2012 / 19:40:49
Checking Folder for postprocessing  Thu 15 Nov 2012 / 19:25:49
Setting permissions on post process script  Thu 15 Nov 2012 / 19:25:46
Copying post process script to Sabnzbd scripts folder   Thu 15 Nov 2012 / 19:25:46
DEBUG : Script Path :[/home/azza/.sabnzbd/scripts]  Thu 15 Nov 2012 / 19:25:46
Searching for games Thu 15 Nov 2012 / 19:25:46
Checking Folder for postprocessing  Thu 15 Nov 2012 / 19:10:49
DEBUG : TheGamesDB ID [11975]   Thu 15 Nov 2012 / 19:01:28
DEBUG : TheGamesDB ID [11119]   Thu 15 Nov 2012 / 19:01:28
DEBUG : TheGamesDB ID [11008]   Thu 15 Nov 2012 / 19:01:28
DEBUG : TheGamesDB ID [None]    Thu 15 Nov 2012 / 19:01:28
DEBUG : TheGamesDB ID [9937]    Thu 15 Nov 2012 / 19:01:28
DEBUG : TheGamesDB ID [11954]   Thu 15 Nov 2012 / 19:01:28
Retrieving the latest version   Thu 15 Nov 2012 / 19:01:23
Checking Folder for postprocessing  Thu 15 Nov 2012 / 19:01:23
Checking to see if a new version is available   Thu 15 Nov 2012 / 19:01:23
DEBUG : TheGamesDB ID [11975]   Thu 15 Nov 2012 / 19:01:23
DEBUG : TheGamesDB ID [11119]   Thu 15 Nov 2012 / 19:01:23
DEBUG : TheGamesDB ID [11008]   Thu 15 Nov 2012 / 19:01:23
DEBUG : TheGamesDB ID [None]    Thu 15 Nov 2012 / 19:01:23
DEBUG : TheGamesDB ID [9937]    Thu 15 Nov 2012 / 19:01:22
DEBUG : TheGamesDB ID [11954]   Thu 15 Nov 2012 / 19:01:22
Retrieving the latest version   Thu 15 Nov 2012 / 19:01:18

**Comment by avjui** [comment]
Have you got the full path under Settings -> Downloders -> SABnzbd+ Download Folder ?

in my case it looks so:

/mnt/Media/Share/ps3

**Comment by aaronflorey** [comment]
Yeah i have. I'm using the same config as when i was using the master branch.

**Comment by avjui** [comment]
Sorry it is a little bit confuse that there is a new option.
Here some picture http://i46.tinypic.com/4lhtvc.png

**Comment by aaronflorey** [comment]
Yeah i got all that filled. http://d.pr/i/bNJr

**Comment by avjui** [comment]
Have you standart folder name in sabnzbd because you have incompleted in the foldername? Should this not be completed?

**Comment by aaronflorey** [comment]
Yeah it stores the games in incomplete, then moves them to incomplete/gamez once done for processing. I really don't know why it isn't working.

**Comment by avjui** [comment]
Have you got a special postprocess script? Have you tested with a other game? You can test to make a folder with the game name. For example add halo 3 and set it to snatched. Then make a folder under incomplete/gamez/Halo 3 (Xbox360) with one underfolder. After that klick on the folder icon on wanted list for helo 3 and look what happend.

**Comment by aaronflorey** [comment]
Alright that works fine now :D wonder why it won't work for Black ops.

Does it download images and stuff yet?

**Comment by avjui** [comment]
Hmm I will test it wich black ops. Maybe the '-' in the folder name is the problem.

To your question with image. No
My problem at the moment is that i look for a small libary for image format changing. Because some picture are in png how should be jpg and other side. But I don´t have find any small libary and I don´t want some special depends like PIL. Maybe you have some idea for this ;-)

**Comment by aaronflorey** [comment]
I spoke to the irc #python channel, and they said there's no way to do this without PIL or another external lib. Only other way you could do, is convert it online.

**Comment by avjui** [comment]
The Thing i can made is that i ignore the picture if it don´t have the right format or i don´t convert the picture. What do you think Gamez should do?

**Comment by aaronflorey** [comment]
That could work, have you tried renaming folder.png to folder.jpg?
