### ISSUE TITLE
Add Ability to snatch different release group

### ISSUE THREAD

**Issue by smidley** [avjui/Gamez#66]
Some games get nuked after they are released.  We should have the ability to retry a download but the program should search for a different NZB in the process.  This way another release group (proper) might be found and downloaded.

**Comment by avjui** [comment]
I am working on this feature but my jquery is not the best ;-)
So standby

**Comment by smidley** [comment]
Glad to hear it's in the works.  :)

**Comment by avjui** [comment]
There we will go on 
https://github.com/avjui/Gamez/issues/60
