### ISSUE TITLE
Special Chars not supported.

### ISSUE THREAD

**Issue by aaronflorey** [avjui/Gamez#67]
The developer branch doesn't support titles with special characters in the name like : or -

**Comment by avjui** [comment]
I think I know what the problem is. I will have a look at this in this evening i hope.

**Comment by avjui** [comment]
That seems the reason why the post processing for this games is not right. I have also a problem with addition words. I will fix this this weekend I hope.

**Comment by avjui** [comment]
At the moment I work on this but it seems that SABnzbd replace ' : ' to ' - ' or is this only with my version?
Please can anybody test with "Call of Duty: Black Ops II (Xbox360)"

**Comment by aaronflorey** [comment]
Yeah that's right, it changes : to - for me aswell. I changed it back to a : and that worked. But windows doesn't support having a ':' in a folder/file name.

**Comment by avjui** [comment]
Please can you test one more, I have add a fix in developer branch. Don´t forgot to delete database.
