### ISSUE TITLE
Multiple items grabbed if using multiple providers

### ISSUE THREAD

**Issue by simonk83** [avjui/Gamez#68]
Just a heads up that I've switched to the developer branch, and have NZBMatrix and nzb.su set up. When a game is grabbed, it's grabbed twice (one from each provider).

**Comment by avjui** [comment]
Can you please say with which game you have tested and which system. So I can tested my self because I don't see any error in the code. Thanks

**Comment by avjui** [comment]
I don´t can confirm this bug here is it alright. I have tested with Halo 3 and it only snatched it from NZBMatrix

**Comment by simonk83** [comment]
Ok, weird.  I'll keep an eye on it.
