### ISSUE TITLE
Newznab provider not working

### ISSUE THREAD

**Issue by ghost** [avjui/Gamez#70]
On nzb.su is working any other newznab provider fail with the error message:

"Error getting game ... from Newznab.

The code from nzb.su is much different than the code for a generic Newznab provider.
Changing the nzb.su URL in GameTasks.py with let's say nzbs.in does work.

Any chance to get this looked at?

thanks

**Comment by avjui** [comment]
First Thanks for testing

Have you got the message ""Unable to connect to Newznab Server: http:// ... " also in the log?
Witch Newznab provider do you use because with my it works?
Do you know if this provider use xml or json api? Because at the moment I always use json for all newznab provider.
Please check you config if there is something wrong.
You also should enable the debug log for more informations.
And at last on witch system are you running Gamez?

**Comment by ghost** [comment]
- No I don't get the Unable to connect message
- I'm using NZBs.in 
- API supports both XML and JSON
- Here the log i get after forcing a search on a game:
  - DEBUG : Newznab Enable
  - Checking for game [A Boy and His Blob] for [Wii] on Newznab
  - DEBUG : Search for http://nzbs.in/api?apikey=_KEY_&t=search&maxage=1100&cat=1030&q=A+Boy+and+His+Blob&o=json
  - Error getting game [A Boy and His Blob] from Newznab

If I try to access the URL http://nzbs.in/api?apikey=_KEY_&t=search&maxage=1100&cat=1030&q=A+Boy+and+His+Blob&o=json it does return some result.

``` javascript
{"@attributes":{"version":"2.0"},"channel":{"title":"NZBs.in","description":"NZBs.in Feed","link":"https:\/\/nzbs.in\/","language":"en-gb","webMaster":"admin@nzbs.in (NZBs.in)","category":{},"image":{"url":"https:\/\/nzbs.in\/views\/images\/banner.jpg","title":"NZBs.in","link":"https:\/\/nzbs.in\/","description":"Visit NZBs.in - The Proud Result of Prison Labor"},"response":{"@attributes":{"offset":"0","total":"1"}},"item":{"title":"A.Boy.And.His.Blob.USA-WII-ProCiSiON","guid":"https:\/\/nzbs.in\/details\/618957b050c0c767cb64ad47e0e3bf54","link":"https:\/\/nzbs.in\/getnzb\/618957b050c0c767cb64ad47e0e3bf54.nzb&i=1&r=API_KEY","comments":"https:\/\/nzbs.in\/details\/618957b050c0c767cb64ad47e0e3bf54#nzb-info-comments","pubDate":"Fri, 04 May 2012 10:03:43 +0100","category":"Console > Wii","description":"A.Boy.And.His.Blob.USA-WII-ProCiSiON","enclosure":{"@attributes":{"url":"https:\/\/nzbs.in\/getnzb\/618957b050c0c767cb64ad47e0e3bf54.nzb&i=1&r=API_KEY","length":"5255787282","type":"application\/x-nzb"}},"attr":[{"@attributes":{"name":"category","value":"1000"}},{"@attributes":{"name":"category","value":"1030"}},{"@attributes":{"name":"size","value":"5255787282"}},{"@attributes":{"name":"guid","value":"618957b050c0c767cb64ad47e0e3bf54"}}]}}}
```
- I'm running Gamez on OSX 10.8

**Comment by avjui** [comment]
Please can you checkout the "Newznab_fix" branch. I have added something. Maybe it is ok else please post me the error output

**Comment by ghost** [comment]
got this error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Users/engine9/Downloads/Gamez-Newznab_fix/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/Users/engine9/Downloads/Gamez-Newznab_fix/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/Users/engine9/Downloads/Gamez-Newznab_fix/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Users/engine9/Downloads/Gamez-Newznab_fix/gamez/WebRoot.py", line 1896, in forcesearch
    GameTasks().ForceSearch(dbid)
  File "/Users/engine9/Downloads/Gamez-Newznab_fix/gamez/GameTasks.py", line 438, in ForceSearch
    GameTasks().FindGames(manualSearchGame,nzbMatrixUser,nzbMatrixApi,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbMatrixEnabled,isNewznabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,isTorrentBlackholeEnabled,isTorrentKATEnabled,torrentBlackholePath,isnzbsuEnable,nzbsuapi,retention)
  File "/Users/engine9/Downloads/Gamez-Newznab_fix/gamez/GameTasks.py", line 79, in FindGames
    isDownloaded = GameTasks().FindGameOnNewznabServer(game_name,game_id,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,system,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,blacklistwords,retention)
  File "/Users/engine9/Downloads/Gamez-Newznab_fix/gamez/GameTasks.py", line 200, in FindGameOnNewznabServer
    nzbTitle = item["title"]
TypeError: string indices must be integers

**Comment by avjui** [comment]
Oh ups I see there are more differences in the responce. It seems that it need a little bit more.

**Comment by avjui** [comment]
Please can you post me a xml example maybe it is easier to build in.

**Comment by ghost** [comment]
xml example of what.

**Comment by avjui** [comment]
Try this line 

 http://nzbs.in/api?apikey=_KEY_&t=search&maxage=1100&cat=1030&q=A+Boy+and+His+Blob&o=json
and change last from json to xml

**Comment by ghost** [comment]
Here's the xml.
But NZBs.in uses the default newznab api, so what works for nzb.su should also work for nzbs.in.

``` rss
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
    <channel>
        <atom:link href="https://nzbs.in/api?apike=API_KEY&t=search&maxage=1100&cat=1030&q=A+Boy+and+His+Blob&o=xml" rel="self" type="application/rss+xml"/>
        <title>NZBs.in</title>
        <description>NZBs.in Feed</description>
        <link>https://nzbs.in/</link>
        <language>en-gb</language>
        <webMaster>admin@nzbs.in (NZBs.in)</webMaster>
        <category/>
        <image>
            <url>https://nzbs.in/views/images/banner.jpg</url>
            <title>NZBs.in</title>
            <link>https://nzbs.in/</link>
            <description>Visit NZBs.in - The Proud Result of Prison Labor</description>
        </image>
        <newznab:response offset="0" total="1"/>
        <item>
            <title>A.Boy.And.His.Blob.USA-WII-ProCiSiON</title>
            <guid isPermaLink="true">
                https://nzbs.in/details/618957b050c0c767cb64ad47e0e3bf54
            </guid>
            <link>
                https://nzbs.in/getnzb/618957b050c0c767cb64ad47e0e3bf54.nzb&i=1&r=API_KEY
            </link>
            <comments>
                https://nzbs.in/details/618957b050c0c767cb64ad47e0e3bf54#nzb-info-comments
            </comments>
            <pubDate>Fri, 04 May 2012 10:03:43 +0100</pubDate>
            <category>Console > Wii</category>
            <description>A.Boy.And.His.Blob.USA-WII-ProCiSiON</description>
            <enclosure url="https://nzbs.in/getnzb/618957b050c0c767cb64ad47e0e3bf54.nzb&i=1&r=API_KEY" length="5255787282" type="application/x-nzb"/>
            <newznab:attr name="category" value="1000"/>
            <newznab:attr name="category" value="1030"/>
            <newznab:attr name="size" value="5255787282"/>
            <newznab:attr name="guid" value="618957b050c0c767cb64ad47e0e3bf54"/>
        </item>
    </channel>
</rss>
```

**Comment by avjui** [comment]
Ok I will look into this on weekend

**Comment by Dingo232** [comment]
Is there any more news on this. I am also having trouble with NZB.SU.

Unable to connect to Newznab Server: http://nzb.su/api?apikey=(removed)&t=search&maxage=1100&cat=1030&q=LEGO+The+Lord+of+the+Rings

If I paste that URL in the IE or FF it loads fine.

Here is the source of the manual paste.

```
<?xml version="1.0" encoding="utf-8" ?> 
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/">
<channel>
<atom:link href="http://nzb.su/api?apikey=(removed)&amp;t=search&amp;maxage=1100&amp;cat=1030&amp;q=LEGO+The+Lord+of+the+Rings" rel="self" type="application/rss+xml" />
<title>Nzb.su</title>
<description>Nzb.su Feed</description>
<link>http://nzb.su/</link>
<language>en-gb</language>
<webMaster>root@nzb.su (Nzb.su)</webMaster>
<category></category>
<image>
    <url>http://nzb.su/views/images/banner.jpg</url>
    <title>Nzb.su</title>
    <link>http://nzb.su/</link>
    <description>Visit Nzb.su - </description>
</image>

<newznab:response offset="0" total="4" />
<item>
    <title>LEGO Lord of the Rings PAL WII-iCON</title>
    <guid isPermaLink="true">http://nzb.su/details/a2d1d9ff8fb8a9fc9758e54aa18ea42e</guid>
    <link>http://nzb.su/getnzb/a2d1d9ff8fb8a9fc9758e54aa18ea42e.nzb&amp;i=97544&amp;r=(removed)</link>
    <comments>http://nzb.su/details/a2d1d9ff8fb8a9fc9758e54aa18ea42e#comments</comments>    
    <pubDate>Thu, 29 Nov 2012 08:40:04 -0500</pubDate> 
    <category>Console &gt; Wii</category>   
    <description>LEGO Lord of the Rings PAL WII-iCON</description>
    <enclosure url="http://nzb.su/getnzb/a2d1d9ff8fb8a9fc9758e54aa18ea42e.nzb&amp;i=97544&amp;r=(removed)" length="5217394453" type="application/x-nzb" />

    <newznab:attr name="category" value="1000" />
    <newznab:attr name="category" value="1030" />
    <newznab:attr name="size" value="5217394453" />
    <newznab:attr name="guid" value="a2d1d9ff8fb8a9fc9758e54aa18ea42e" />


</item>
<item>
    <title>LEGO Lord of the Rings USA WII-VIMTO</title>
    <guid isPermaLink="true">http://nzb.su/details/a912e0085db40c3fea2bc9f403afe3de</guid>
    <link>http://nzb.su/getnzb/a912e0085db40c3fea2bc9f403afe3de.nzb&amp;i=97544&amp;r=(removed)</link>
    <comments>http://nzb.su/details/a912e0085db40c3fea2bc9f403afe3de#comments</comments>    
    <pubDate>Wed, 21 Nov 2012 02:30:29 -0500</pubDate> 
    <category>Console &gt; Wii</category>   
    <description>LEGO Lord of the Rings USA WII-VIMTO</description>
    <enclosure url="http://nzb.su/getnzb/a912e0085db40c3fea2bc9f403afe3de.nzb&amp;i=97544&amp;r=(removed)" length="5210706893" type="application/x-nzb" />

    <newznab:attr name="category" value="1000" />
    <newznab:attr name="category" value="1030" />
    <newznab:attr name="size" value="5210706893" />
    <newznab:attr name="guid" value="a912e0085db40c3fea2bc9f403afe3de" />


</item>
<item>
    <title>LEGO Lord of the Rings Wii USA Flabado)</title>
    <guid isPermaLink="true">http://nzb.su/details/8001f189bdccabb2fe9453a938cb3fa3</guid>
    <link>http://nzb.su/getnzb/8001f189bdccabb2fe9453a938cb3fa3.nzb&amp;i=97544&amp;r=(removed)</link>
    <comments>http://nzb.su/details/8001f189bdccabb2fe9453a938cb3fa3#comments</comments>    
    <pubDate>Mon, 19 Nov 2012 02:28:33 -0500</pubDate> 
    <category>Console &gt; Wii</category>   
    <description>LEGO Lord of the Rings Wii USA Flabado)</description>
    <enclosure url="http://nzb.su/getnzb/8001f189bdccabb2fe9453a938cb3fa3.nzb&amp;i=97544&amp;r=(removed)" length="4205502942" type="application/x-nzb" />

    <newznab:attr name="category" value="1000" />
    <newznab:attr name="category" value="1030" />
    <newznab:attr name="size" value="4205502942" />
    <newznab:attr name="guid" value="8001f189bdccabb2fe9453a938cb3fa3" />


</item>
<item>
    <title>GG 932 Lego Lord of the Rings NTSC-PAL</title>
    <guid isPermaLink="true">http://nzb.su/details/03acd0a6d1475c2853981cdac4939971</guid>
    <link>http://nzb.su/getnzb/03acd0a6d1475c2853981cdac4939971.nzb&amp;i=97544&amp;r=(removed)</link>
    <comments>http://nzb.su/details/03acd0a6d1475c2853981cdac4939971#comments</comments>    
    <pubDate>Sun, 18 Nov 2012 12:03:44 -0500</pubDate> 
    <category>Console &gt; Wii</category>   
    <description>GG 932 Lego Lord of the Rings NTSC-PAL</description>
    <enclosure url="http://nzb.su/getnzb/03acd0a6d1475c2853981cdac4939971.nzb&amp;i=97544&amp;r=(removed)" length="4149606593" type="application/x-nzb" />

    <newznab:attr name="category" value="1000" />
    <newznab:attr name="category" value="1030" />
    <newznab:attr name="size" value="4149606593" />
    <newznab:attr name="guid" value="03acd0a6d1475c2853981cdac4939971" />


</item>

</channel>
</rss>
```

**Comment by avjui** [comment]
Sorry, but at the moment I have no time to update this. I hope I will fix this next week when I have some free days. So please stay tuned.

**Comment by Dingo232** [comment]
Ok, thank you very much :)

**Comment by Markyb0y** [comment]
any update on this issue? I am still facing the same issue with any newsnab provider

**Comment by avjui** [comment]
Please can someone test the dirty fix in the Newznab_fix Branch. Notice there is python 2.7 necessary for this fix.
Because I dont can test it here

**Comment by avjui** [comment]
@ dingo232

There is a separatly section for nzb.su in the option please try this

**Comment by lad1337** [comment]
about newznab fix i tried a little myself see my fork or specifically https://github.com/lad1337/Gamez/commit/dfd9fca40dcb36bfcff18443e1ae75e0041f5ed2
i only tested this with the newznab server at nzbs2go.com ... it is working for me and there are is some more stuff i changed ... the ini file will needs manual additions in oder for the branch to work

**Comment by avjui** [comment]
It looks ok but what is with the old api. I have a server with old and so it dose  not work any more.

**Comment by avjui** [comment]
I have added your change in a other way. Big Thanks

**Comment by Markyb0y** [comment]
@avjui 
added it to the gamesdb branch?

**Comment by avjui** [comment]
When it work yes but at the moment it is in the Newznab_fix

**Comment by avjui** [comment]
Have  any one  test this changes?

**Comment by qdecosne** [comment]
I get a 500 Internal Server Error if I do a Force Search

``` python
Traceback (most recent call last):
  File "/Users/quentin/Development/gamez/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/Users/quentin/Development/gamez/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/quentin/Development/gamez/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/quentin/Development/gamez/gamez/WebRoot.py", line 1896, in forcesearch
    GameTasks().ForceSearch(dbid)
  File "/Users/quentin/Development/gamez/gamez/GameTasks.py", line 460, in ForceSearch
    GameTasks().FindGames(manualSearchGame,nzbMatrixUser,nzbMatrixApi,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbMatrixEnabled,isNewznabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,isTorrentBlackholeEnabled,isTorrentKATEnabled,torrentBlackholePath,isnzbsuEnable,nzbsuapi,retention)
  File "/Users/quentin/Development/gamez/gamez/GameTasks.py", line 79, in FindGames
    isDownloaded = GameTasks().FindGameOnNewznabServer(game_name,game_id,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,system,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,blacklistwords,retention)
  File "/Users/quentin/Development/gamez/gamez/GameTasks.py", line 225, in FindGameOnNewznabServer
    nzbTitle = item["title"]
TypeError: string indices must be integers
```

**Comment by qdecosne** [comment]
and here's what i have in my log when it does a schedule search:

```
Searching for game: A Boy and His Blob
DEBUG : Newznab Enable
Checking for game [A Boy and His Blob] for [Wii] on Newznab
DEBUG : Search for http://nzbs.in/api?apikey=___&t=search&maxage=1100&cat=1030&q=A+Boy+and+His+Blob&o=json
Major error occured when running scheduled tasks - - string indices must be integers -
```

**Comment by avjui** [comment]
Please can you test one commit before with the changes I made. Thanks

**Comment by avjui** [comment]
Hey guys I need you because I don´t can test it. Please can any one test this version 
https://github.com/avjui/Gamez/tree/9e238919694a60ad23c2ae79da01c43313a00253
Thanks

**Comment by qdecosne** [comment]
a force search gives me this=

``` python
Traceback (most recent call last):
  File "/Users/quentin/Development/gamez/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/Users/quentin/Development/gamez/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/quentin/Development/gamez/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/quentin/Development/gamez/gamez/WebRoot.py", line 1896, in forcesearch
    GameTasks().ForceSearch(dbid)
  File "/Users/quentin/Development/gamez/gamez/GameTasks.py", line 462, in ForceSearch
    GameTasks().FindGames(manualSearchGame,nzbMatrixUser,nzbMatrixApi,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbMatrixEnabled,isNewznabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,isTorrentBlackholeEnabled,isTorrentKATEnabled,torrentBlackholePath,isnzbsuEnable,nzbsuapi,retention)
  File "/Users/quentin/Development/gamez/gamez/GameTasks.py", line 79, in FindGames
    isDownloaded = GameTasks().FindGameOnNewznabServer(game_name,game_id,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,system,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,blacklistwords,retention)
  File "/Users/quentin/Development/gamez/gamez/GameTasks.py", line 228, in FindGameOnNewznabServer
    nzbUrl = link.replace('API_KEY', newznabApi)
NameError: global name 'link' is not defined
```

**Comment by avjui** [comment]
Next try. I hope it work. I don´t can test this.

**Comment by ghost** [comment]
``` python
Traceback (most recent call last):
  File "/Users/engine9/Development/gamez/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/Users/engine9/Development/gamez/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/engine9/Development/gamez/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/engine9/Development/gamez/gamez/WebRoot.py", line 1896, in forcesearch
    GameTasks().ForceSearch(dbid)
  File "/Users/engine9/Development/gamez/gamez/GameTasks.py", line 462, in ForceSearch
    GameTasks().FindGames(manualSearchGame,nzbMatrixUser,nzbMatrixApi,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbMatrixEnabled,isNewznabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,isTorrentBlackholeEnabled,isTorrentKATEnabled,torrentBlackholePath,isnzbsuEnable,nzbsuapi,retention)
  File "/Users/engine9/Development/gamez/gamez/GameTasks.py", line 79, in FindGames
    isDownloaded = GameTasks().FindGameOnNewznabServer(game_name,game_id,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,system,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,blacklistwords,retention)
  File "/Users/engine9/Development/gamez/gamez/GameTasks.py", line 234, in FindGameOnNewznabServer
    if not str(blacklistword) in nzbTitle or blacklistword == '':
UnboundLocalError: local variable 'nzbTitle' referenced before assignment
```

Why can't you re-use the code for NZB.su?
They use the standard newznab API so what's work for .su should work for other newznab indexer.

What can't you test it? do you need access to another newznab indexer?

**Comment by avjui** [comment]
@ engine9tm next try

And yes I don´t have a access to another newznab.

Thanks

**Comment by ghost** [comment]
still the same error 

``` python
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Users/engine9/Development/gamez/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/Users/engine9/Development/gamez/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/engine9/Development/gamez/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/engine9/Development/gamez/gamez/WebRoot.py", line 1896, in forcesearch
    GameTasks().ForceSearch(dbid)
  File "/Users/engine9/Development/gamez/gamez/GameTasks.py", line 462, in ForceSearch
    GameTasks().FindGames(manualSearchGame,nzbMatrixUser,nzbMatrixApi,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbMatrixEnabled,isNewznabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,isTorrentBlackholeEnabled,isTorrentKATEnabled,torrentBlackholePath,isnzbsuEnable,nzbsuapi,retention)
  File "/Users/engine9/Development/gamez/gamez/GameTasks.py", line 79, in FindGames
    isDownloaded = GameTasks().FindGameOnNewznabServer(game_name,game_id,sabnzbdApi,sabnzbdHost,sabnzbdPort,newznabWiiCat,newznabApi,newznabHost,newznabPort,system,newznabXbox360Cat,newznabPS3Cat,newznabPCCat,sabnzbdCategory,isSabEnabled,isNzbBlackholeEnabled,nzbBlackholePath,blacklistwords,retention)
  File "/Users/engine9/Development/gamez/gamez/GameTasks.py", line 234, in FindGameOnNewznabServer
    if not str(blacklistword) in nzbTitle or blacklistword == '':
UnboundLocalError: local variable 'nzbTitle' referenced before assignment
```

**Comment by avjui** [comment]
Please can you post me the response of this search? It like that there was nothing find. Is there any of this provider where i can get a free account?

**Comment by avjui** [comment]
Please can you test main "TheGamedb". I have change some code. ;-)

**Comment by Markyb0y** [comment]
just wanted to leave a quick comment that my gamez has just started pulling nzbs from Newznab

Good Job!

**Comment by avjui** [comment]
Nice so I will pull it for all

**Comment by Dingo232** [comment]
I just noticed the recent emails.

I have just downloaded the new files and replaced them. I ticked the nzb.su box and entered my key but I still get an error. 

Unable to connect to Newznab Server: http://nzb.su/api?apikey=(removed)&t=search&maxage=1100&cat=1050&q=Big+League+Sports
DEBUG : Serach URL [http://nzb.su/api?apikey=(removed)&t=search&maxage=1100&cat=1050&q=Big+League+Sports]

The link works ok if I paste it into a browser as before.

**Comment by avjui** [comment]
Please can you test with the newznab box again. I think this code is also good for nzb.su. When this where ok i replace the nzb.su code also with the new one.

**Comment by Markyb0y** [comment]
Newznab download the game fine for me, but I then see an error in SABNZBD which I assume is to do with the post processing script

{"Error": " Status was not updatet"}

so firstly the script is failing somehow, so it doesnt go from snatched to downloaded in Gamez

and second there is a spelling mistake it should be updated, and not updatet

at least its downloading again :)
thanx

**Comment by avjui** [comment]
Hmm Thats strange. Because the new version dont need the postprocess script any more. It check Sabnzbd history over the api. Please delete the database of gamez and the postprocess script and test. The spelling error I will fix in the next commit

**Comment by Dingo232** [comment]
I filled out the newznab section and now I get these entries in the log.

Error getting game [Marvel Avengers Battle for Earth] from Newznab

DEBUG : Search for http://nzb.su/api?apikey=(removed)=search&maxage=1100&cat=1050&q=Marvel+Avengers+Battle+for+Earth&o=json

If i check that url i get one line of text as follows.

{"@attributes":{"version":"2.0"},"channel":{"title":"Nzb.su","description":"Nzb.su Feed","link":"http:\/\/nzb.su\/","language":"en-gb","webMaster":"root@nzb.su (Nzb.su)","category":{},"image":{"url":"http:\/\/nzb.su\/views\/images\/logo.png","title":"Nzb.su","link":"http:\/\/nzb.su\/","description":"Visit Nzb.su - "},"response":{"@attributes":{"offset":"0","total":"3"}},"item":[{"title":"Marvel.Avengers.Battle.for.Earth.XBOX360-iMARS","guid":"http:\/\/nzb.su\/details\/31e103af943504489505b606ba0ccec8","link":"http:\/\/nzb.su\/getnzb\/31e103af943504489505b606ba0ccec8.nzb&i=97544&r=(removed)","comments":"http:\/\/nzb.su\/details\/31e103af943504489505b606ba0ccec8#comments","pubDate":"Tue, 30 Oct 2012 18:42:29 -0400","category":"Console > Xbox 360","description":"Marvel.Avengers.Battle.for.Earth.XBOX360-iMARS","enclosure":{"@attributes":{"url":"http:\/\/nzb.su\/getnzb\/31e103af943504489505b606ba0ccec8.nzb&i=97544&r=(removed)","length":"9632350925","type":"application\/x-nzb"}},"attr":[{"@attributes":{"name":"category","value":"1000"}},{"@attributes":{"name":"category","value":"1050"}},{"@attributes":{"name":"size","value":"9632350925"}},{"@attributes":{"name":"guid","value":"31e103af943504489505b606ba0ccec8"}}]},{"title":"Marvel.Avengers.Battle.for.Earth.XBOX360-iMARS","guid":"http:\/\/nzb.su\/details\/ce79a24bee555f49271a2df0e7dc24a1","link":"http:\/\/nzb.su\/getnzb\/ce79a24bee555f49271a2df0e7dc24a1.nzb&i=97544&r=(removed)","comments":"http:\/\/nzb.su\/details\/ce79a24bee555f49271a2df0e7dc24a1#comments","pubDate":"Tue, 30 Oct 2012 09:02:45 -0400","category":"Console > Xbox 360","description":"Marvel.Avengers.Battle.for.Earth.XBOX360-iMARS","enclosure":{"@attributes":{"url":"http:\/\/nzb.su\/getnzb\/ce79a24bee555f49271a2df0e7dc24a1.nzb&i=97544&r=(removed)","length":"9390262568","type":"application\/x-nzb"}},"attr":[{"@attributes":{"name":"category","value":"1000"}},{"@attributes":{"name":"category","value":"1050"}},{"@attributes":{"name":"size","value":"9390262568"}},{"@attributes":{"name":"guid","value":"ce79a24bee555f49271a2df0e7dc24a1"}}]}]}}

**Comment by avjui** [comment]
I need the output with o=xml instant o=json on the end of command. When the Debug log has this link it seems that you must update your games on last git stand.

**Comment by ghost** [comment]
@Dingo232 you might want to generate a new api key.

**Comment by Dingo232** [comment]
@engine9tm thank you, I thought I had removed them before I pasted. New key has been generated.

@avjui I just grabbed the latest version. I do not get any error now but i do nothing else happens either. This is the output from the link.

```
<?xml version="1.0" encoding="utf-8" ?> 
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/">
<channel>
<atom:link href="https://nzb.su/api?apikey=(removed)&amp;t=search&amp;maxage=1100&amp;cat=1050&amp;q=Marvel+Avengers+Battle+for+Earth&amp;o=xml" rel="self" type="application/rss+xml" />
<title>Nzb.su</title>
<description>Nzb.su Feed</description>
<link>https://nzb.su/</link>
<language>en-gb</language>
<webMaster>root@nzb.su (Nzb.su)</webMaster>
<category></category>
<image>
    <url>https://nzb.su/views/images/logo.png</url>
    <title>Nzb.su</title>
    <link>https://nzb.su/</link>
    <description>Visit Nzb.su - </description>
</image>


<newznab:response offset="0" total="3" />
<item>
    <title>Marvel.Avengers.Battle.for.Earth.XBOX360-iMARS</title>
    <guid isPermaLink="true">https://nzb.su/details/31e103af943504489505b606ba0ccec8</guid>
    <link>https://nzb.su/getnzb/31e103af943504489505b606ba0ccec8.nzb&amp;i=97544&amp;r=(removed)</link>
    <comments>https://nzb.su/details/31e103af943504489505b606ba0ccec8#comments</comments>   
    <pubDate>Tue, 30 Oct 2012 18:42:29 -0400</pubDate> 
    <category>Console &gt; Xbox 360</category>  
    <description>Marvel.Avengers.Battle.for.Earth.XBOX360-iMARS</description>
    <enclosure url="https://nzb.su/getnzb/31e103af943504489505b606ba0ccec8.nzb&amp;i=97544&amp;r=(removed)" length="9632350925" type="application/x-nzb" />

    <newznab:attr name="category" value="1000" />
    <newznab:attr name="category" value="1050" />
    <newznab:attr name="size" value="9632350925" />
    <newznab:attr name="guid" value="31e103af943504489505b606ba0ccec8" />


</item>
<item>
    <title>Marvel.Avengers.Battle.for.Earth.XBOX360-iMARS</title>
    <guid isPermaLink="true">https://nzb.su/details/ce79a24bee555f49271a2df0e7dc24a1</guid>
    <link>https://nzb.su/getnzb/ce79a24bee555f49271a2df0e7dc24a1.nzb&amp;i=97544&amp;r=(removed)</link>
    <comments>https://nzb.su/details/ce79a24bee555f49271a2df0e7dc24a1#comments</comments>   
    <pubDate>Tue, 30 Oct 2012 09:02:45 -0400</pubDate> 
    <category>Console &gt; Xbox 360</category>  
    <description>Marvel.Avengers.Battle.for.Earth.XBOX360-iMARS</description>
    <enclosure url="https://nzb.su/getnzb/ce79a24bee555f49271a2df0e7dc24a1.nzb&amp;i=97544&amp;r=(removed)" length="9390262568" type="application/x-nzb" />

    <newznab:attr name="category" value="1000" />
    <newznab:attr name="category" value="1050" />
    <newznab:attr name="size" value="9390262568" />
    <newznab:attr name="guid" value="ce79a24bee555f49271a2df0e7dc24a1" />


</item>

</channel>
</rss>
```
