### ISSUE TITLE
"Unable to connect to KickAss Torrents"?

### ISSUE THREAD

**Issue by franner** [avjui/Gamez#75]
I tried with several games as a test but gamez writes "Unable to connect to KickAss Torrents" in the log. Any idea why that can be?

**Comment by pabloamg** [comment]
I know your comment is old, but probably is because it is looking for kickasstorrent.com not kickass.to (wich is the current site for Kickass Torrent)  the url is in GameTasks.py line 321 

```
-       url = "http://www.kickasstorrents.com/json.php?q=" + game_name
+       url = "http://www.kickass.to/json.php?q=" + game_name
```

**Comment by avjui** [comment]
Thanks, I have change it
