### ISSUE TITLE
Launch browser on startup option

### ISSUE THREAD

**Issue by faintuk** [avjui/Gamez#8]
Just wondering if you would consider adding a launch browser on startup similar to what can be found in sick beard/couch potato

**Comment by avjui** [comment]
I would have a look at this. I am working on the console option.

**Comment by avjui** [comment]
Please can you explain me what this option is doing exactly?

**Comment by faintuk** [comment]
When I start gamez I click on the "gamez.py" file and this brings up a command prompt style box giving details on gamez, I then have to open a new tab in my Internet browser and type in http://localhost:8085 into the address bar and then this gives me access to the GUI of gamez and from here I can start using gamez

I would like it so when I click the "gamez.py" file it will open the command style box but then also automatically open up my internet browser and load http://localhost:8085

I believe headphones / couch potato / sickbeard all have this feature

**Comment by avjui** [comment]
Ok I add some code. Please can you test it

**Comment by faintuk** [comment]
ive downloaded the lastest version and tested it but from what i can see nothing has changed, i click the games.py file and it loads but nothing else happens and i still have to manually open my browser and type the address in

**Comment by avjui** [comment]
Hi

I have forgot to import the function. Please can you checkout the new Version an test. Here it is ok.

**Comment by faintuk** [comment]
another job well done, working great

cheers

**Comment by KruyKaze** [comment]
Can we make this optional? I just have a bookmark for Gamez and I don't need it to open a browser tab every time it's launched or updated.

**Comment by avjui** [comment]
You can start Gamez with the option --nolaunch, then this feature is disable

**Comment by KruyKaze** [comment]
nice thank you.

On Sat, May 5, 2012 at 10:43 AM, avjui
reply@reply.github.com
wrote:
